DROP TABLE IF EXISTS park_entrance_pass;
CREATE TABLE park_entrance_pass(
   uid         INTEGER NOT NULL PRIMARY KEY 
  ,cost        NUMERIC
  ,description VARCHAR
  ,title       VARCHAR
);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Valid for 12 months from purchase date. This pass provides access to Acadia National Park only. This pass admits the pass holder and passengers in a non-commercial vehicle.','Acadia Annual Pass',1);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',2);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no park-specific passes required or sold at this location.','Park Specific Passes',3);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Non','Passes',4);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There is no fee or pass required for use of this park.','Monument Pass',5);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (4.00,'If you are using a motorized boat on the lake you will need to purchase a Lake Use Pass. They can be purchased at the Visitor Center or by using the fee machines located at Diablo East, Box Canyon, Rough Canyon, and campgrounds. All purchases are by credit or debit only.','Daily Lake Use Pass',6);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (50.00,'If you are using a motorized boat on the lake you will need to purchase a Lake Use Pass. They can be purchased at the Visitor Center or by using the fee machines located at Diablo East, Box Canyon, Rough Canyon, and at campgrounds. All purchases are by credit or debit only.

**Yearly Lake Use Passes purchased at the fee machines are temporary yearly passes and must be exchanged for a boat sticker at the Visitor Center.**','Yearly Lake Use Pass',7);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no entrance passes for this park.','Entrance Passes',8);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Because no fees are charged at the park, no entrance passes are available at Andersonville National Historic Site.','Entrance Passes',9);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'As the Andrew Johnson National Historic Site is free, there is no distribution of or need for annual passes.','Entrance passes not available',10);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Interagency Lifetime Senior Pass:  $80 Lifetime.  This is a pass for U.S. Citizens or permanent residents, age 62 or over. This pass provides access to, and the use of Federal recreation sites that charge an Entrance or Standard Amenity Fee*. This pass admits the pass holder and passengers in a non-commercial vehicle at per vehicle areas and pass holder plus 3 adults at per person fee areas.','Interagency Lifetime Senior Pass',11);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Interagency Access Pass:  Valid for life. This is a lifetime pass for U.S. Citizens or permanent resident with permanent disabilities. Documentation is required to obtain the pass. This pass provides access to, and use of Federal recreation sites that charge an entrance fee.','Interagency Access Pass',12);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for one year from month of purchase for Antietam National Battlefield only. Admits pass holder and passengers in a single private vehicle.','Antietam National Battlefield Annual Pass',13);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This is a free pass to active duty military personal and their dependents. In order to qualify for the pass, the military member must present a valid Department of Defense, CAC Card. Dependents must present a valid Department of Defense ID (DD Form 1173) that identifies the dependent and his or her sponsor. Some members of the Military Reserve might not be eligible.','Interagency Military Pass',14);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Interagency Annual Senior Pass:  $20 Annually.  This is a pass for U.S. Citizens or permanent residents, age 62 or over. This pass provides access to, and the use of Federal recreation sites that charge an Entrance or Standard Amenity Fee*. This pass admits the pass holder and passengers in a non-commercial vehicle at per vehicle areas and pass holder plus 3 adults at per person fee areas.','Interagency Annual Senior Pass',15);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Fourth grade students and their families can benefit from free admission to fee-collecting parks, public lands and waters by downloading a paper pass from the Every Kid Outdoors website. In addition, if the 4th grader would like to exchange the paper passes for a more durable "keepsake" Fourth Grade Annual Pass, they may do so at the park''s visitor center from 9:00 to 4:00 daily.','4th Grade Student Pass',16);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'0','0',17);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for one year through the month of purchase. Admits one (1) private, non-commercial vehicle or its pass holder to Arches and Canyonlands national parks, and Natural Bridges and Hovenweep national monuments.','Southeast Utah Parks Pass',18);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Valid for 1 year from month of purchase for entry to Assateague Island National Seashore (MD) and Chincoteague National Wildlife Refuge (VA). Purchased at Assateague Island National Seashore (MD) and the Toms Cove Visitor Center (VA).','Assateague Island National Seashore Annual Pass',19);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Valid for 1 year from month of purchase for entry to Chincoteague National Wildlife Refuge (VA) and Island National Seashore (MD). Purchased at the Chincoteague National Wildlife Refuge (VA).','Chincoteague National Wildlife Refuge Annual Pass',20);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Chincoteague National Wildlife Refuge Annual Beach Parking Permit combined with the Federal Duck Stamp (valid for 1 year, July 1 to June 30, at all National Wildlife Refuges) will gain entry into Assateague Island National Seashore (MD) and Chincoteague National Wildlife Refuge (VA) for 1 vehicle.  Purchased at the Chincoteague National Wildlife Refuge (VA).','Chincoteague National Wildlife Refuge Annual Beach Parking Permit',21);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'This pass admits a single, private, non commercial vehicle and its occupants into the park. This pass does not include camping or give any type of discount at stores inside the park. Valid for one year from month of purchase.','Badlands National Park Annual Pass',22);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (25.00,'General monument admission. Good for 7 days','7 Day Vehicle Entry',23);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (15.00,'Pass for individual entering the park on foot or on bicycle. If ariving on shuttle, and visitor walked to the shuttle from parking other than the shuttle parking, individual pass applies when entering the park.','Individual/Bicycle',24);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Entrance fee is for one motorcycle and passenger.','Motorcycle',25);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Pass for one year of vehicle entry to Bandelier','Bandelier Annual Pass',26);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Passes are not required to enter this Park. 

For groups of 10 people or more, please contact us at 202-543-2240 to schedule your visit.','No Passes Required',27);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (10.00,'Per Person - Adults (age 16 and older): $10.00
Children (age 15 and under): Free

All park visitors are required to pay an entrance fee or have a valid federal recreation pass to recreate in the park, including walking on the trails.

Entrance fees can be paid to a ranger at the entrance of the fort (credit card only) or at the Western National Parks Association (WNPA) park store in the back of the fort (all forms of tender accepted). Permits are good for seven consecutive days. Fees apply to those 16 years','Bent''s Old Fort Entrance Fee',28);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Covers entrance fees for passholder plus three adults at Bent''s Old Fort National Historic Site. This pass can be purchased at the entrance inside the fort and at the Western National Parks Association park store in the back of the fort. Good for one year from purchase. Non-transferable and non-refundable.','Bent''s Old Fort Annual Pass',29);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'The Big Bend Annual Pass covers entrance fees to Big Bend National Park. Pass is available at Big Bend National Park entrance stations or the Panther Junction Visitor Center. Pass is non-transferable.','Big Bend Annual Pass',30);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no entrance fees to Big Hole National Battlefield or Bear Paw Battlefield.','Entrance Passes',31);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No entrance fees.','No entrance fees.',32);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'This pass admits the permit holder and all accompanying passengers in a single, private, noncommercial vehicle to the park. It is valid for 12 months from date of purchase and covers entry fees only.','Black Canyon Annual Pass',33);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'At this time, annual passes cannot be purchased from the Blackstone River Valley National Historical Park as we do not have a store yet.','Annual Pass',34);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Entrance Passes because park has free admission','No Entrance Passes because park has free admission',35);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no entrance passes for this site.  Ranger guided walking tours are free of charge.  Our partner, the Museum of African American History charges an admission fee.','There are no entrance passes for this site.',36);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Valid for twelve months from the date of purchase, for unlimited visits to Bryce Canyon National Park. It admits the purchaser and any accompanying persons in a single, private, non-commercial vehicle, or the purchaser and accompanying immediate family (spouse, children, parents) when entry is by other means (shuttle, bicycle, and foot). This pass covers entrance fees only and is not refundable and/or transferable.','Bryce Canyon Annual Pass',37);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Buy your pass in advance! Visit www.Recreation.gov and search for Bryce Canyon National Park Site Pass','Digital Entrance Pass',38);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Entrance Pass','No Entrance Pass',39);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for 12 months from purchase date. Admits the pass holder(s) and passengers in a non-commercial vehicle (14 passenger capacity or less) to Cabrillo National Monument. The pass is available at the Entrance Station.

Park passes are available at the Entrance Station until 4:20pm.','Cabrillo Annual Pass',40);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (40.00,'Park-specific pass. Admits pass holder and all persons in a single, private, non-commercial vehicle to Canaveral National Seashore. Valid for 12 months from when the pass is purchased.','Canaveral National Seashore Annual Pass',41);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for one year through the month of purchase. Admits one (1) private, non-commercial vehicle or its pass holder to Arches and Canyonlands national parks, and Hovenweep and Natural Bridges national monuments.','Southeast Utah Parks Annual Pass',42);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (60.00,'This pass provides private vehicle entrance into the six beach parking lots managed by the national seashore for the entirety of the park''s charging season. This pass is in the form of a sticker affixed to the windshield of a vehicle and is not transferable. Purchase at beach entrance stations during business hours. Fees are typically collected at the six beaches from late spring through the end of September.','Annual Private Vehicle Beach Entrance Pass to Cape Cod National Seashore',43);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Pass Required','No Pass Required',44);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This pass covers the entrance fees to Capitol Reef National Park of the pass holder and occupants of a single, private non-commercial vehicle. It is valid for 365 days from the date of purchase. For information about other passes available see https://www.nps.gov/care/planyourvisit/fees.htm.','Capitol Reef Annual Pass',45);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This pass covers the entrance fees for the pass holder''s vehicle. It is valid for 365 days from the date of purchase.','Capulin Volcano Annual Pass',46);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Pass Required','No Pass Required',47);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'One year admission pass for the card holder and up to three additional adults.','Castillo Annual Pass',48);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no park-specific passes required or sold at this location.','Park Specific Passes',49);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Castle Mountains is a fee free area.','Castle Mountains Pass',50);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Admission to Cedar Breaks National Monument for one year from date of purchase. 

This pass covers the entrance fee for the purchaser and three additional people 16 years of age or older. Admission for children 15 &under is free.','Cedar Breaks Annual Pass',51);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (5.00,'A CRNRA Daily Park Pass allows a single, private, non-commercial vehicle (car/truck/van) to enter the park for one day. The vehicle must park in a designated parking lot. You may purchase a CRNRA Daily Park Pass online at https://www.recreation.gov/sitepass/2626 or in person at Island Ford Visitor Center. Valid America The Beautiful Passes are also valid for parking in the park.','CRNRA Daily Park Pass',52);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (40.00,'The Annual Park Pass allows a single, private, non-commercial vehicle (car/truck/van) to park in any designated parking lot of the park during regular park hours for one year. You may purchase an Annual Park Pass online at https://www.recreation.gov/sitepass/2626 or in person at Island Ford Visitor Center. A valid America The Beautiful Pass are is also valid for parking in the park','Annual Park Pass',53);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for one full year from the month of purchase. Permits access to Great Falls Park, Virginia and the Great Falls area of the Chesapeake and Ohio Canal National Historical Park on the Maryland side of the Potomac River. The annual pass allows entrance for the pass holder and additional passengers in a single private non-commercial vehicle, or pass holder plus three adults when entering on foot or bicycle.

<a href=https://www.recreation.gov/sitepass/111897>Purchase online </a>','Great Falls Annual Pass',54);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Visitors who purchase a Point Park Annual Pass can visit Point Park on an unlimited basis throughout the year. The pass allows entry to the park for the pass owner and three other individuals. 

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','Point Park Annual Pass',55);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'A lifetime pass for citizens or permanent residents of the US, age 62 or older. One person can sign the pass. 

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','Lifetime Senior Pass',56);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'An annual pass valid 12 months from month of purchase. Two people can sign the pass. 

*current US Military Members and 4th graders are eligible for different annual passes*

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','Annual Pass',57);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'A lifetime pass for citizens or permanent residents of the US who have a permanent disability, regardless of age. One person can sign the pass.

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','Access Pass',58);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'A yearly pass for citizens or permanent residents of the US, age 62 or older. One person can sign the pass. Four annual Senior Passes purchased in consecutive years can be traded in for a lifetime pass.

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','Annual Senior Pass',59);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'A yearly pass for students in the 4th grade. You must complete the activities at www.everkidinapark.gov and present a printed voucher to be exchanged for a pass. 

Please note that pass availability might vary from day to day. If you are planning on visiting Point Park to purchase a pass, please call the Lookout Mountain Battlefield Visitor Center at 423-821-7786 to confirm pass availability that day.','4th Grade Pass',60);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'This annual pass covers entrance fees at national parks and national wildlife refuges and standard amenity day use fees at national forests and grasslands, and at lands and waters managed by the Bureau of Land Management, the Bureau of Reclamation, and the Army Corps of Engineers. It admits the pass owner and their accompanying passengers, or three (3) adults. The Annual Pass costs $80.00','America the Beautiful – The National Parks and Federal Recreational Lands Pass',61);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This is a no-fee lifetime pass for individuals with permanent disabilities. This pass will get the cardholder plus 3 additional persons age 16 and older entry to Fort Christiansvaern. Applicants must provide documentation of permanent disability and residency or citizenship.','Access Pass',62);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This pass is available only for active duty military personnel and dependents with proper identification (Common Access Card or Military ID/Form 1173). The Annual Military Pass may be obtained at the visitor booth at Fort Christiansvaern.','Annual Pass for U.S. Military',63);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'This pass for U.S. citizens and permanent residents age 62 and older will get the cardholder plus three (3) additional persons age 16 and older entry to Fort Christiansvaern. Passes are sold at the visitor booth in Fort Christiansvaern. The Lifetime Pass costs $80, and the Annual Senior Pass is available for $20.','America the Beautiful – The National Parks and Federal Recreational Lands Senior Pass - $20.00 (Annual), $80.00 (Lifetime)',64);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No entrance passes are required.','Civil War Defenses of Washington',65);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No fees, pass not required','No fees, pass not required',66);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Covers entrance fees for any two passholders and accompanying passengers in a single, private, non-commercial vehicle at Colorado National Monument. This pass can be purchased at either entrance to Colorado National Monument. Good for one year from purchase. This pass does not cover camping fees. Non-transferable and non-refundable.','Colorado National Monument Annual Pass',67);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',68);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid only at Crater Lake National Park and Lava Beds National Monument. The Crater Lake annual pass is good for one year from the issue month. It admits the pass owner and accompanying passengers in a single, private, noncommercial vehicle or pass owner and three persons when entry is by other means.','Crater Lake Annual Pass',69);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This pass covers the entrance fees of the pass holder and up to three fellow travelers. It is valid for 365 days from date of purchase. Available in spring 2016.','Craters Annual Pass',70);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'The pass is good for one calendar year from month of purchase. The pass admits the pass holder plus three additional adults. Pass can be purchased at mainland visitor center.  Debit/credit cards only.','Cumberland Island National Seashore Annual Pass',71);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Annual pass providing free entrance to Death Valley for 12 months from the date of purchase','Death Valley Annual Pass',72);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Valid for 12 months from date of purchase, for entry into Devils Tower National Monument only.','Devils Tower National Monument Annual Pass',73);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'This pass is available to the general public and provides access to, and use of, Federal recreation sites that charge an Entrance or Standard Amenity Fee for a year, beginning from the date of sale. The pass admits the pass holder/s and passengers in a non-commercial vehicle at per vehicle fee areas and pass holder + 3 adults, not to exceed 4 adults, at per person fee areas. (children under 16 are admitted free)','America the Beautiful - National Parks and Federal Recreational Lands Pass-Annual Pass',74);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'This is a lifetime pass for U.S. citizens or permanent residents age 62 or over. The pass provides access to, and use of, Federal recreation sites that charge an Entrance or Standard Amenity. The pass admits the pass holder and passengers in a non-commercial vehicle at per vehicle fee areas and pass holder + 3 adults, not to exceed 4 adults, at per person fee areas (children under 16 are admitted free). The pass can only be obtained in person at the park.','American the Beautiful - National Parks and Federal Recreation Lands Pass-Senior Pass (Lifetime)',75);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'This is an annual pass for U.S. citizens or permanent residents age 62 or over. The pass provides access to, and use of, Federal recreation sites that charge an Entrance or Standard Amenity. The pass admits the pass holder and passengers in a non-commercial vehicle at per vehicle fee areas and pass holder + 3 adults, not to exceed 4 adults, at per person fee areas (children under 16 are admitted free). The pass can only be obtained in person at the park.','America the Beautiful – National Parks and Federal Recreational Lands Pass–Senior Pass (Annual)',76);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This is a lifetime pass for U.S. citizens or permanent residents with permanent disabilities. Documentation is required to obtain the pass. Acceptable documentation includes: statement by a licensed physician; document issued by Federal agency such as the Veteran''s Administration, Social Security Disability Income or Supplemental Security Income; or document issued by a State agency such as a vocational rehabilitation agency.','America the Beautiful - National Parks and Federal Recreational Lands Pass-Access Pass',77);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This pass is for volunteers acquiring 250 service hours on a cumulative basis. Contact the Chief of Interpretation at 307-467-5283 ext. 224 to learn about volunteer opportunities in Devils Tower National Monument.','America the Beautiful - National Parks and Federal Recreational Lands Pass-Volunteer Pass',78);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Valid for 12 months from purchase date.
Admits the pass holder/s and passengers in a non-commercial vehicle(14 passenger capacity or less) to Dinosaur National Monument.','Dinosaur Annual Pass',79);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (15.00,'Enjoy the convenience of purchasing an digital pass on Recreation.gov before you arrive. You have immediate access to your digital pass and can easily download it on your phone or tablet. Your pass will also be emailed as a PDF and can be printed out for display when you arrive.

To purchase online go to https://www.recreation.gov/sitepass/2665','Entrance Passes',80);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',81);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Passes are not required or sold at this site. Entrance is by reservations only.','Eugne O''Neill National Historic Site',82);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'The Annual Pass for the Everglades National Park is valid for 12 months starting from the day of purchase and is good for unlimited visits to the park during this period. These passes can be purchased at the Homestead and Shark Valley entrance stations or the Gulf Coast and Flamingo Visitor Centers. You can also purchase the senior park pass or pass for entry into all national parks at these locations.','Everglades National Park Annual Pass',83);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no park-specific passes required or sold at this location.','Park Specific Passes',84);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'First State National Historical Park does not sell or accept park passes, because we are a fee-free park.','First State Passes',85);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Good for cardholder and 3 other adults (16 and older) to Florissant Fossil Beds NM.  Good for one year from purchase date.','Florissant Fossil Beds Annual Pass',86);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'You can buy an annual pass to Fort Davis National Historic Site for $35.00. This pass will admit the pass owners and three other adults to the Fort for 12 months from the month of purchase.','Fort Davis Annual Pass',87);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Passes are not needed at Fort Donelson National Battlefield, as we have no fees.

Free annual pass for the military may be found at this site:
https://www.nps.gov/subjects/military/entrance-passes.htm

Passes are not issued at Fort Donelson, but may be purchased at Land Between the Lakes, a few minutes away.

http://www.landbetweenthelakes.us/','No entrance fees at Fort Donelson',88);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Fort Larned does not charge entrances fees.','Entrance',89);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Fort Larned does not charge entrances fees.','Entrance',90);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'NO FERRY SERVICE ON MONDAY & TUESDAY

A free ferry service takes passengers to Fort Matanzas at half past every hour.  Each tour leaves the dock at half past every hour.  First at 9:30am and the Last at 3:30pm.  Boarding passes are issued from the Visitor Center on a first come basis.','Ferry Passes',91);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'The America the Beautiful Interagency Annual Pass may be purchased by anyone and is valid for one year following the month of purchase. The pass covers entrance fees for the pass holder and three adult guests.','America the Beautiful: Interagency Annual Pass',92);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'The Interagency Senior Lifetime Pass is a lifetime pass for American citizens ages 62 and over. The pass covers the admission of the pass holder and three adult guests. Senior Lifetime Passes do not expire.','Interagency Senior Lifetime Pass',93);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'The Interagency Senior Annual Pass is an annual pass for U.S. seniors aged 62 or older. The pass covers the admission of the pass holder and three adult guests. Senior Annual Passes are valid for one year from the month of purchase.','Interagency Senior Annual Pass',94);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The Interagency Access Pass is a lifetime pass for any citizen or permanent resident of the U.S. who has been medically determined to have a permanent disability. The pass covers the admission of the pass holder and three adult guests. Access Passes do not expire.','Interagency Access Pass',95);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The Interagency Military Pass is an annual pass for current U.S. military members and their dependents with a valid U.S. Department of Defense CAC card or DoD Form 1173 for proof of identification.The pass covers the admission of the pass holder and three adult guests. The pass is valid for one year from the month that it is issued.','Interagency Military Pass',96);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The Interagency 4th Grade Annual Pass is for 4th graders including home-schooled and free-choice learners. The pass covers the admission of the pass holder and three adult guests. The pass is valid from September through August of the year that the student is in the 4th grade.

Students may obtain a pass with a printed voucher from the Every Kid in a Park website. A paper voucher must be presented in order to receive a pass.','Interagency 4th Grade Annual Pass',97);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'America the Beautiful: Interagency Lifetime Military Pass - $0.00
The Lifetime Military Pass is for veterans and gold star families. The pass covers the admission of the pass holder and three adult guests (16 years old and older). The pass does not expire. To qualify veterans must show a valid form of ID indicating their veteran status, and gold star families must present a printed voucher. This pass is NOT availble online and must be requested on site.','Interagency Military Lifetime Pass',98);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass covers the pass holder plus three adult guests to Fort McHenry for a year. The pass can be purchased on site or on recreation.gov.','Fort McHenry Annual Pass',99);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'The Fort Pulaski Annual Pass covers the pass holder and three additional people for admission to the monument for one full year. Credit or Debit Cards Only. Digital passes can be purchased at https://www.recreation.gov/sitepass/2699','Fort Pulaski Annual Pass',100);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'The annual pass allows the pass holder and 3 adults (16 and older) free entrance to all the exhibits in the visitor center. The pass is valid for 12 months from the month of purchase, expiring the last day of that month.','Fort Smith National Historic Site Annual Pass',101);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Annual Pass for Fort Moultrie valid for pass holder and three additional adults. Valid for one year from purchase date. The Fort Moultrie Pass is available for purchase at https://www.recreation.gov/sitepass/2704. Fort Moultrie is currently not accepting cash for entrance fees.','Fort Moultrie Annual Pass',102);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',103);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No entrance passes required.','No Entrance Pass',104);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Lifetime 50% discount for beach parking for visitors 62 and older.','Senior Pass',105);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Golden Access Passes are free, and offer lifetime access to citizens and permanent residents who have been medically determined to have a permanent disability.  Golden Access Pass holders will receive a 50% discount for parking at both Sandy Hook and Jacob Riis Park.  You can obtain these passes at any Gateway visitor center as well as at other national parks.','Golden Access Passes',106);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Annual pass covering entrance fees for 4th grade students. 5th grade students are included through August 31, 2021.','Every Kid Outdoors',107);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Free parking available for those active US military personnel and their families as well as U.S. military veterans and their families.','Interagency military pass',108);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There is no fee to enter Gauley River National Recreation Area, so there is no need for an entrance pass. Enjoy your visit!','Entrance Passes',109);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes Available For Sale','No Passes Available For Sale',110);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Gila Cliff Dwellings does not sell any passes, nor do we provide Access, Veteran, Military or 4th Grade passes.','No passes available',111);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Gila Cliff Dwellings does not sell any passes, nor do we provide Access, Veteran, Military or 4th Grade passes.','No passes available',112);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'This pass is valid for one year from the month of entry and admits the purchaser and passengers in a single, private, non-commercial vehicle, or the pass holder and his/her immediate family (spouse, children, parents) when entry is by other means (foot, bicycle) into the park. It is nontransferable, nonrefundable, and does not cover camping fees.','Glacier National Park Annual Pass',113);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'This pass is valid for one year from the month of entry and admits the purchaser and passengers in a single, private, non-commercial vehicle, or the pass holder and his/her immediate family (spouse, children, parents) when entry is by other means (foot, bicycle) into the park. It is nontransferable, nonrefundable, does not cover camping fees and  cannot be replaced if lost or stolen.','America the Beautiful Annual Pass',114);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Available for U.S. citizens or permanent residents age 62 or over. Applicants must provide documentation of age and residency or citizenship.','America the Beautiful Senior Lifetime Pass',115);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Available for U.S. citizens or permanent residents age 62 or over. Applicants must provide documentation of age and residency or citizenship.
This pass is only valid for one year. Four Annual Senior Passes may be exchanged for a free Lifetime Senior Pass.','America the Beautiful Senior Annual Pass',116);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Free to U.S. 4th Graders (including home-schooled and free-choice learners 10 years of age).
Valid for the duration of the 4th grade school year (September - August).
Students must have a paper voucher printed from the Every Kid Outdoors to obtain the Annual 4th Grade Pass. Digital versions of the voucher (such as smart phones or tablets) will not be accepted.','America the Beautiful Every Kid Outdoors Pass',117);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This is a lifetime pass for U.S. citizens or permanent residents with permanent disabilities. Documentation is required to obtain the pass. Acceptable documentation includes: statement by a licensed physician; document issued by Federal agency such as the Veteran''s Administration, Social Security Disability Income or Supplemental Security Income; or document issued by a State agency such as a vocational rehabilitation agency.','America the Beautiful Access Pass',118);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available to active duty military personnel and dependents, veterans and Gold Star Families with proper identification (CAC Card or DD Form 1173, VHIC, Veteran ID Card or Gold Star Family access voucher).
The pass admits the pass owners and any accompanying passengers in a private non-commercial vehicle at per vehicle fee areas, or the pass owner and up to additional 3 adults at sites that charge per person.','America the Beautiful Military Pass',119);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This pass is for volunteers acquiring 250 service hours on a cumulative basis. It provides access to, and use of, Federal recreation sites that charge an Entrance or Standard Amenity Fee for a year, beginning from the date of award.

Contact our Volunteer Coordinator at 406-888-7851 to learn about volunteer opportunities in Glacier or visit volunteer.gov.','America the Beautiful Volunteer Pass',120);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Allows unlimited entry to Glen Canyon for 12 months from date of purchase.','Glen Canyon National Recreation Area Annual Pass',121);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (50.00,'Allows unlimited entry to Glen Canyon for one motorized vessel for one calendar year. If a Senior Pass is presented at time of purchase, the annual vessel sticker fee is $25.','Glen Canyon National Recreation Area Annual Vessel Sticker',122);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'no entrance pass, no entrance fee','no entrance pass, no entrance fee',123);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This is an annual pass that covers entrance fees at Golden Spike National Historical Park for the pass holder and occupants within a single noncommercial vehicle OR the pass holder and three persons (16 and older) where per person fees apply. This pass is available to anyone 16 or older.

The Agencies are NOT responsible for misplaced, lost or stolen cards. 

The pass can be signed by two pass holders.','Golden Spike National Historical Park Annual Pass',124);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Valid for twelve months from the date of purchase, for unlimited visits to Grand Canyon National Park. It admits the purchaser and any accompanying persons in a single, private, non-commercial vehicle, or the purchaser and accompanying immediate family (spouse, children, parents) when entry is by other means (train, shuttle, bicycle, and foot).','Grand Canyon National Park Annual Pass',125);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Pass is valid for one year through the month of purchase. Park Annual Pass provides entrance to pass holder and accompanying passengers in a single private non-commercial vehicle to Grand Teton National Park. Purchase your pass at one of Grand Teton''s park entrances and permits desks at the Craig Thomas Discovery and Visitor Center and the Colter Bay Visitor Center.','Grand Teton Annual Pass',126);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for twelve months from the date of purchase. Pass is valid at Great Falls Park and Chesapeake and Ohio Canal National Historical Park for entrance fee only. Admits the pass holder and occupants of a single, private non-commercial vehicle OR pass holder and three persons (16 and older) where per person entrance fees are charged.','Great Falls Annual Pass',127);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Covers one family''s entrance for 12 months from time of purchase. Valid for two adults with signatures plus others in vehicle.','Great Sand Dunes Annual Family Pass',128);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This pass is valid for entrance into Guadalupe Mountains National Park for one year from the month of purchase. The pass admits up to four adults in a private vehicle and is non-transferable; visitors under 16 years of age are free. You can purchase this pass at the Pine Springs Visitor Center.','Guadalupe Mountains National Park Annual Pass',129);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Guilford Courthouse is a Fee-Free site, meaning you can enjoy the park for free!

The park sells Interagency Park Passes in the Battlefield Visitors Center.','No Pass Required',130);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Covers all areas in Gulf Islands National Seashore charging an entrance fee until the end of the month one year after purchase. This pass can be purchased at the Fort Pickens Entrance Station, Perdido Key Entrance Station, and Davis Bayou Campground.','Gulf Islands National Seashore Annual Pass',131);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for 12 months from purchase date. Admits the pass holder/s and passengers in a non-commercial vehicle (14 pax capacity or less) to Haleakala National Park, Hawai‘i Volcanoes National Park and Pu`uhonua O Hōnaunau National Historical Park. All other National Parks in Hawai‘i are free entry.','Hawai‘i Tri-Park Annual Pass',132);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for one year from month of purchase for Harpers Ferry NHP only. Admits pass-holder and passengers in a single, private vehicle (excluding groups) or immediate family if entering by other means. Nontransferable.

Annual passes can be purchased at the Entrance Station near the park''s visitor center.','Harpers Ferry Annual Pass',133);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'An annual tri-park pass allows access for 1 full year from date of first use at Hawai‘i Volcanoes National Park, Haleakalā National Park, and Pu‘uhonua o Hōnaunau National Historical Park.','Hawai‘i Tri-Park Pass',134);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Holders of the following passes will be admitted to Historic Jamestowne at 
Description*
* Interagency Access and Golden Access Pass
* Interagency Military Pass
Phone 757-856-1250 for further information.','No Additional Charge for Holders of These Passes',135);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There is no charge to visit Horseshoe Bend National Military Park.','Fees',136);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for one year through the month of purchase. Admits one (1) private, non-commercial vehicle or its pass holder to Arches National Park, Canyonlands National Park, Natural Bridges National Monument, and Hovenweep National Monument.','Southeast Utah Group Annual Pass',137);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Some sites associated with the Ice Age Floods National Geologic Trail are operated by federal partners. America the Beautiful passes are honored by National Park Service, US Forest Service, US Fish and Wildlife Service, Bureau of Reclamation, US Army Corps of Engineers, and the Bureau of Land Management.','America the Beautiful - The National Parks and Federal Recreational Lands Pass Series',138);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'A National Park Pass is not required to enjoy the Ice Age National Scenic Trail, Some public lands such as state and county parks located along the Trail may charge entrance fees. Camping registration, permits, and fees may also be needed. Before your visit you should check with the local land manager regarding possible fees and registration requirements.','Passes',139);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Timed entry tickets are required to visit Independence Hall from March through December.  Tickets must be reserved through recreation.gov.  There is a $1 per ticket service fee.','Timed Entry Tickets for Independence Hall',140);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass provides entry for the pass owner(s) and passengers in a family-sized vehicle.  This pass only works at the Indiana Dunes National Park and is not accepted at the Indiana Dunes State Park.','Indiana Dunes National Park Annual Pass',141);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (60.00,'Valid from April 16 - October 31 of the year indicated. Covers the entrance fee ($7 per person per day) for the person whose signature appears on the pass and up to 3 adults (aged 16 and up) traveling with the pass holder. Non-refundable and non-transferable. Can be obtained in-person from the Houghton, Rock Harbor, or Windigo Visitor Centers or online at www.pay.gov, search Isle Royale Season Pass and click on "Continue to Form."','Isle Royale Season Pass',142);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Passes are not require and are not sold at this location.','John Muir National Historic Site',143);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'This pass is valid for 12 months from the month of purchase. It covers the entrance fee to Joshua Tree National Park for the pass signee and accompanying passengers entering in a single, non-commercial vehicle. Joshua Tree Annual Passes are available at park entrance stations and visitor centers.','Joshua Tree National Park Annual Pass',144);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The 1,200-mile Anza Trail connects historic, cultural, and recreation sites from Nogales, AZ, to the San Francisco Bay Area that reveal the legacy of our Spanish colonial heritage. To learn more, visit http://www.nps.gov/juba. Each site along the Anza Trail is managed independently. Contact individual sites for hours, directions, and other details.','Passes Vary by Site',145);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'All visitors to Kalaupapa must obtain a visitor permit, which can be acquired by making reservations with Kekaula Tours (808) 567-6088 or Saint Damien & Mother Marianne Cope Molokai Tours (808) 895-1673.','Visitor Permit issued by the State of Hawaii Department of Health',146);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Katahdin Woods and Waters National Monument is a fee free area.','Fee free',147);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No entrance passes are necessary to enter Katmai.','None',148);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (5.00,'Kennesaw Mountain NBP charges for entrance to the park. This is a per vehicle entrance fee. Any vehicle parked at Kennesaw Mountain will be required to purchase a $5 daily pass online or a $40 annual pass (online or at Visitor Center). Digital passes purchased online at Recreation.gov will be tied to a specific license plate; physical passes purchased at Visitor Center will be displayed in the vehicle. America the Beautiful Interagency Passes are also accepted. Purchases can be made with CARD ONLY, not cash','Kennesaw Mountain Day Pass',149);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (40.00,'Kennesaw Mountain NBP charges for entrance to the park. This is a per vehicle entrance fee. Any vehicle parked at Kennesaw Mountain will be required to purchase a $5 daily pass online or a $40 annual pass (online or at Visitor Center). Digital passes purchased online at Recreation.gov will be tied to a specific license plate; physical passes purchased at Visitor Center will be displayed in the vehicle. America the Beautiful Interagency Passes are also accepted. Purchases can be made with CARD ONLY, not cash','Kennesaw Mountain Annual Pass',150);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',151);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No entrance passes are necessary to enter Lake Clark National Park and Preserve.','None',152);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Admits passholder and occupants of a single, private non-commercial vehicle. In cases where per person fees are charged, pass is valid for the passholder + 3 adults. An Annual Pass permits entrance for two motorcycles IF the two people who sign the pass arrive at the same time on two motorcycles, regardless of the number of people on each motorcycle. Valid for one year from month of purchase.','Annual Pass - Vehicle, Motorcycle or Individual',153);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (50.00,'Per vessel. Valid through Dec. 31 of year purchased','Annual Pass - Vessel',154);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for one year from month of purchase at Lassen Volcanic National Park and Whiskeytown National Recreation Area. Passes may be purchased as park entrance stations mid-May through October.','Lassen Annual Pass',155);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'The annual pass is good for one year at both Lava Beds National Monument and Crater Lake National Park.','Lava Beds & Crater Lake Annual Pass',156);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Pass covers entry, vehicle parking, and day use fees at all Oregon state and federal fee sites along the Oregon Coast.','Annual Oregon Pacific Coast Passport',157);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',158);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Annual pass covering entrance and standard amenity fees for national parks and other federal fee areas; Valid for 1 year through the month of purchase.','Interagency Annual Pass:',159);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Annual pass covering entrance and standard amenity fees for all national parks and other federal fee areas. Free to US military personnel and their dependents with proper identification (current CAC Card or qualified DD Form 1173 required).','Interagency Annual Pass for US Military: Free',160);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available to U.S. 4th Graders (including home-schooled and free-choice learners 10 years of age). Valid for the duration of the 4th grade school year through the following summer (September to August).','Interagency 4th Grader Pass: Free',161);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Lifetime admission and discount pass for U.S. citizens or permanent residents who are age 62 and older.','Interagency Senior Lifetime Pass:',162);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Annual pass covering entrance and standard amenity fees for national parks and other federal fee areas; Valid for 1 year through the month of purchase.','Interagency Senior One Year Annual Pass:',163);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Annual pass for volunteers with 250 cumulative service hours with federal agencies that participate in the Interagency Pass Program.','Interagency Volunteer Pass: Free',164);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Lifetime admission and discount pass for U.S. citizens or permanent residents with documentation of permanent disability.','Interagency Access Pass: Free',165);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Give the user unlimited access during operating hours during a calendar year (January - December). Located near Cedar Bluff, Alabama. Instead of paying $15 per vehicle, purchase the pass for a year for $35. Amenities included paved parking lot, restrooms, picnic tables, grills, lots of shade, close to the water, and a playground. 

America the Beautiful passes are also valid at Canyon Mouth Park and will allow access using the fee machine or when park staff are present at the booth.','Canyon Mouth Park picnic area Annual Pass',166);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (15.00,'Located near Cedar Bluff, Alabama, the Canyon Mouth Park area features amenities including a paved parking lot, restrooms with sinks and flush toilets, picnic tables, grills, lots of shade, close to the water, and a brand new playground.

A seven-day pass costs $15 and an annual pass costs and is good for one vehicle. 

A machine is available at the entrance to Canyon Mouth Park should no park personnel be present in the booth. The machine takes cash only.','Canyon Mouth Park picnic area Daily Pass',167);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'As an affiliated National Park Site, the Lower East Side Tenement Museum does not accept the America the Beautiful - Annual Pass, the America the Beautiful - Senior Pass, the America the Beautiful - Access Pass, the America the Beautiful - Volunteer Pass, or the Every Kid Outdoor - 4th Grade Pass.  
The Lower East Side Tenement Museum also does not sell National Parks Passes.','National Parks Passes',168);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (85.00,'Members receive free admission to tours, exclusive events, and specialty content! Learn more about membership at https://www.tenement.org/membership/','Tenement Museum Membership Pass',169);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (85.00,'Members receive free admission to tours, exclusive events, and specialty content! Learn more about membership at https://www.tenement.org/membership/','Tenement Museum Membership Pass',170);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No pass is required to enter Manzanar National Historic Site. Enjoy your visit!

If you plan to visit other parks with an entrance fee, learn more about the National Parks and Federal Recreation Lands Passes.','Entrance Passes',171);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',172);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Pass Required','No Pass Required',173);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'The annual pass provides entrance into Mesa Verde National Park for a year, beginning from the date of sale. It covers the entrance fee for the pass holder and anyone in their vehicle.','Mesa Verde Annual Pass',174);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'This is a lifetime pass for U.S. citizens or permanent residents with permanent disabilities. Documentation is required to obtain the pass. Acceptable documentation includes: statement by a licensed physician; document issued by Federal agency such as the Veteran''s Administration, Social Security Disability Income or Supplemental Security Income; or document issued by a State agency such as a vocational rehabilitation agency.','Access Pass',175);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for current U.S. military members and dependents in the Army, Navy, Air Force, Marines, and Coast Guard as well as Reserve and National Guard members. Please bring a Common Access Card or Military ID (Form 1173)','Free Annual Pass for U.S. Military',176);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for U.S. 4th graders (including home-schooled and free-choice learners 10 years of age) with a valid Every Kid Outdoors paper pass. Paper passes can be obtained by visiting the Every Kid Outdoors website and can be exchanged for the Annual 4th Grade Pass at federal recreation sites that charge Entrance or Standard Amenity fees (Day Use Fee)','Annual 4th Grade Pass',177);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'The Montezuma Castle and Tuzigoot Annual Pass covers the card holder and 3 other adults (aged 16 and over) into both Montezuma Castle and Tuzigoot for one year from date of purchase.','Montezuma Castle and Tuzigoot Annual Pass',178);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Entrance Passes','No Entrance Passes',179);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Grants unlimited entry for one year to pass owner and passengers in the same car.','Mount Rainier Annual Pass',180);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass admits the pass holder and three guests into Muir Woods. This pass is good for one year. Purchase physical passes at the Muir Woods Visitor Center or purchase digital passes on www.recreation.gov','Muir Woods Annual Pass',181);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No passes are required for any of the memorials on the National Mall with the exception of the Washington Monument, which requires a timed ticket for entry.','No Passes required for sites at National Mall and Memorial Parks, except Washington Monument',182);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The Washington Monument Lodge, located along 15th Street between Madison and Jefferson drives, opens at 8:45 a.m. for distribution of free, same day, timed tickets on a first-come, first-serve basis. One person may obtain up to six tickets as well as request their preferred ticket time. All visitors (including children ages 2+) must have a ticket to enter the Washington Monument. During peak season, tickets run out quickly. Note: Many visitors form a line to wait long before the ticket window open.','Washington Monument Walk-up Tickets (Same Day Only)',183);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Order tickets online up to a month in advance of your visit. Inventory for the next available day (30 days out) becomes available at 10 a.m. each morning (e.g. - on May 7 at 10 a.m., tickets will become available for visits on June 6).','Online Advance Tickets- 30 Day Advance Reservations',184);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Didn''t get tickets in advance or planning a last minute visit? A limited number of additional tickets are made available at 10 a.m. each day for the next day''s visits (e.g. - on May 7 at 10 a.m., tickets will become available for visits on May 8).','Same Day Walkup - 24-Hour Advance Reservations',185);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Contact recreation.gov or by calling 877-444-6777. Though there is no admission fee for the Washington Monument, there is a $1.00 service charge per ticket to cover reservation service; these fees are NON-REFUNDABLE. Ticket availability is limited and all tickets for a given day are often reserved the day they become available.','Both 30 Day Advance and 24 Hour Advance reservations',186);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Groups may reserve up to 55 tickets up to 30 days in advance at recreation.gov ONLY. No walk ups are available for group tours. There is a $1.00 service charge per ticket to cover the reservation service.

Please plan ahead: All visitors MUST print their tickets in advance or have their tickets available to view on a mobile device. Please review printing directions in the Need to Know section.','Group Tickets (Online Only)',187);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Since there are no fees or reservations required, entrance passes are all waived.','Entrance Pass',188);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'While none of the eleven parks within the National Parks of New York charge an entrance fee, some parks may charge for certain amenities such as parking at beach areas and camping. Be sure to check the park specific webpage to learn more about fees they may charge if you are interested in visiting.','NPNH Entrance Pass',189);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Valid for one year through the month of purchase. Admits one (1) private, non-commercial vehicle or its pass holder to Arches National Park, Canyonlands National Park, Natural Bridges National Monument, and Hovenweep National Monument.','Southeast Utah Parks Annual Pass',190);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The park does not charge a fee for entrance, camping, guided or back-country hiking.  Donations are welcomed.','Fee & Park Pass',191);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Since this is not a fee park, park passes, senior passes, and access passes are not available for purchase here. If you plan to visit other national parks with an entrance fee, passes can be purchased online at www.nps.gov, or at any park that charges an entrance fee.','Passes',192);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'North Cascades National Park Service Complex does not sell entrance passes because no entry fee is required to enjoy the park.','North Cascades National Park Service Complex Entrance Passes',193);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'We do not carry the Entrance Passes at the park.','No Entrance Passes Available at Ocmulgee Mounds NHP',194);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'The Olympic National Park Annual Pass costs $55 and is good for entry into the park for one year from the month of purchase. Passes can be purchased at Olympic National Park visitor centers and entrance stations.','Olympic National Park Annual Pass',195);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (10.00,'The park does not charge an entrance fee,but there is a separate amenity fee to take a cave tour.Annual entrance fee passes do not apply,(e.g.America the Beautiful and other annual passes)Persons with Senior and Access passes receive a half price discount for the card holder (only).Senior and Access pass holders must present their pass at the ticket counter (including for reservations).','Cave Tour Fees',196);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'A year-long entrance pass for Organ Pipe Cactus National Monument.','Annual Pass',197);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (25.00,'An Entrance Pass covering all the occupants of one vehicle.','Vehicle Pass',198);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'An Entrance Pass covering all the occupants of a motorcycle.','Motocycle Pass',199);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (15.00,'An entrance pass covering one pedestrian or bicyclist.','Individual Pass',200);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Admits the passholder and up to 15 passengers in the same private (non-commercial)vehicle or motorcycle.It expires one year from the month of purchase.','Padre Island Annual Pass',201);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (30.00,'Allows one private vehicle and/or trailer to park at the Bird Island Basin Boat Ramp.Valid one year from the month of purchase.','Bird Island Basin Boat Ramp Annual Pass',202);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Entrance passes are not required nor are they available at this site.','None required',203);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',204);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'This pass grants holder and 3 accompanying adults admission to Memorial Observation Deck. The pass is good for 1 year.','Perry''s Victory and International Peace Memorial Annual Pass',205);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Good for a private vehicle and its occupants for a year.','Petrified Forest National Park Annual Pass',206);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Valid for 12 months from purchase date.This pass provides access to Pictured Rocks National Lakeshore only.This pass admits the pass holder and passengers in a non-commercial vehicle.','Pictured Rocks Annual Pass (increasing to $30.00 January 1,2023)',207);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available to U.S.military members and dependents in the Army,Navy,Air Force,Marine Corps,Coast Guard,Reserve,and National Guard members.
Must be obtained in person at a Federal recreation site by showing a Common Access Card (CAC)or Military ID (Form 1173).','U.S.Military Annual Pass',208);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'For U.S.citizens or permanent residents age 62 or over.Applicants must provide documentation of age and residency or citizenship.
May provide a 50 percent discount on some amenity fees.Does NOT cover or reduce special recreation permit fees or fees charged by concessionaires.','Senior Inter-Agency Annual Pass',209);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Admits the purchaser and their passengers in a single,private,non-commercial vehicle or the pass holder and their companions when entry is by other means (i.e.foot,bicycle).Nontransferable,nonrefundable,and does not cover camping fees.','Pinnacles National Park Annual Pass',210);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Can be obtained in person at a federal recreation site,or by calling 1-888-ASK USGS (1-888-275-8747),Ext.3 (Hours of operation are:8:00 am to 4:00 pm Mountain time).Or online by visiting the USGS store.http://store.usgs.gov/This Pass is non-transferable.','Annual Inter-Agency Pass',211);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'For U.S.citizens or permanent residents age 62 or over.Applicants must provide documentation of age and residency or citizenship.
May provide a 50 percent discount on some amenity fees.Does NOT cover or reduce special recreation permit fees or fees charged by concessionaires.','Senior Inter-Agency Lifetime Pass',212);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'U.S.citizens or permanent residents with permanent disabilities.Applicants must provide documentation of permanent disability and residency or citizenship.','Access Pass',213);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'For U.S.4th graders (including home-schooled and free-choice learners 10 years of age).','Every Kid Outdoors Pass',214);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Park passes are not sold or required for reservations.Reservations are free.','Port Chicago Naval Magazine National Memorial',215);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'0','0',216);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Provides unlimited entry to the park for one year through the month of purchase.Provides entry for pass holders and occupants of a single personal vehicle (capacity of 14 passengers or less).For walk-ins pass is good for holder and 4 additional people.','Prince William Forest Park Annual Pass',217);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Allows access for 12 months from date of purchase at Pu‘uhonua o Hōnaunau National Historical Park.

The pass admits the pass owner and/or spouse along with accompanying persons in a single,private,non-commercial vehicle.

When entry is by other means (bicycle,foot,Hele-On bus,etc.)the pass covers the purchaser and accompanying immediate family (spouse,children,and parents).Pass is not refundable or transferable.','Puʻuhonua o Hōnaunau Annual Pass',218);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Allows access for one full year from date of purchase.Hawaiʻi Tri-Park Pass is valid at Puʻuhonua o Hōnaunau National Historical Park,Hawaiʻi Volcanoes National Park and HaleakalāNational Park.','Hawaiʻi Tri-Park Annual Pass',219);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'As there are no fees for Rainbow Bridge, there is no pass.','Annual Pass',220);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Rock Creek Park Does not have any entrance passes','Rock Creek Park Entrance Passes',221);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Unlimited entry for one year from date of purchase.','Rocky Mountain National Park Annual Pass',222);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'This pass covers the entrance fee to all national parks, as well as US Fish & Wildlife Service and also standard amenity fees (day use fees) at lands managed by the US Forest Service, Bureau of Land Management, Bureau of Reclamation, and US Army Corps of Engineers. A pass covers the pass owner and all occupants in a personal vehicle at sites that charge per vehicle or, the pass owner and up to three additional adults (16 and over) at sites that charge per person. Children ages 15 or under are admitted free.','America the Beautiful Interagency Annual Pass',223);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Available for: US citizens or permanent residents ages 62 or over. Applicants must provide documentation of age and residency or citizenship.','America the Beautiful Interagency Senior Annual Pass',224);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Available for: US citizens or permanent residents ages 62 or over. Applicants must provide documentation of age and residency or citizenship.','America the Beautiful Interagency Senior Lifetime Pass',225);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for: US citizens or permanent residents with permanent disabilities. Applicants must provide documentation of permanent disability and residency or citizenship. This pass is valid for the passholder''s lifetime.','America the Beautiful Access Pass',226);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for current US military members and their dependents in the Army,Navy,Air Force,Marines,Coast Guard,and Space Force,as well as Reserve and National Guard members.Please check photo ID requirements before arriving.','America the Beautiful Military Annual Pass',227);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for Gold Star Families with a valid Gold Star Family Voucher and US military veterans with a valid,veteran ID.','America the Beautiful Military Lifetime Pass',228);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available for US 4th graders,including home-schooled and free-choice learners 10 years of age,with a valid Every Kid Outdoors paper voucher','America the Beautiful 4th Grade Pass',229);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'You can receive Military, Access and 4th Grade Passes at the Visitor Centers.','Military, Access and 4th Grade Passes',230);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Park passes are not required and not sold at this location.','No Passes Required/ Passes not available',231);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Valid for 12 months from the date of purchase, for unlimited visits to Saguaro National Park, in Tucson, Arizona.   May be purchased at either district or online from www.nps.gov/sagu/payfee.htm.

Admits purchaser and any accompanying persons in a single, private, non-commercial vehicle, or pass holder and three persons (16 & older) where per person entrance fees are charged. This passport covers entrance fees only and is not refundable and/or transferable.','Saguaro National Park Annual Pass',232);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Entrance is free. As this site is an affiliated site, NPS passes are not available.','Saint Paul''s Church passes',233);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (40.00,'An annual park pass,specifically for Saint-Gaudens National Historic Site,is available for $40.As a"walk in"park,all of these passes allow the pass holder and three other adults entry to the park (must be present at the time with passholder).','Saint-Gaudens NHS Annual Pass',234);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'All U.S. fourth grade students and their families with free admission to thousands of federal lands and waters. The pass is valid from September 1 through August 31 of the following year. The paper voucher or the pass allows free entry for fourth graders and three accompanying adults (in a single, private vehicle) at federally managed, U.S. participating sites.','Every Kid Outdoors 4th Grade Pass',235);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Good for one year. Only valid for San Francisco Maritime National Historical Park. The pass holder may enter with three additional adults and any number of children 15 years old and younger.','Annual Park Pass',236);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Annual pass valid only for San Juan National Historic Site.Valid for cardholder and 3 additional adults.','San Juan NHS Annual Pass',237);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'This pass is valid for Sequoia & Kings Canyon National Parks and Hume Lake Ranger District of Sequoia National Forest/Giant Sequoia National Monument for one year from the month of purchase. The pass admits all passengers in a private vehicle and is non-transferable.','Sequoia & Kings Canyon Annual Pass',238);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Provides unlimited entry for one year to the pass holder and passengers in the same vehicle, not to exceed 4 total adults. Children under 16 are admitted for free and are not included in this total.','Shenandoah Annual Pass',239);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Admits pass holder and all passengers in a noncommercial vehicle. Valid for one year from month of purchase. 
Cashless payments at all staffed locations. Cash accepted at self-pay stations.

Valid for 12 months from month of issue.
When purchased at an Automated Pay Station, please exchange the receipt for the Annual Park Pass card at any staffed fee collection station.','Annual Park Entrance Pass',240);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Entry to Springfield Armory National Historic Site is free of charge. 

Springfield Armory offers the following free passes:
Free Annual Pass for current US Military and their dependents
Free Annual Pass for US 4th Grade Students
Free Lifetime Access Pass for US Citizens or permanent residents medically determined to have a permanent disability.

The Park does not sell National Park Passes but they my be purchased at fee-based parks or online at: 
https://www.nps.gov/planyourvisit/passes.htm','America The Beautiful Passes',241);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass is valid for one year from the month of purchase. At Sunset Crater Volcano and Wupatki National Monuments, it covers entry for all occupants of one private vehicle. At Walnut Canyon National Monument, it covers entry for up to four adults; children ages 15 and younger enter for free.','Flagstaff Annual Pass',242);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There are no National Park Service passes required nor sold at this location.','Park Specific Passes',243);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Must show pass upon entry.  Admits pass holder and up to three other adults.  Pass accepted for entry, but not sold here.','NPS Annual',244);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Must show pass upon entry.  Admits pass holder and up to three other adults.  Pass accepted for entry, but not sold here.','NPS Access',245);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Must show pass upon entry.  Admits pass holder and up to three other adults.  Pass accepted for entry, but not sold here.','NPS Senior',246);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Must show pass or military ID upon entry.  Admits pass holder and up to three other adults.  Pass accepted for entry, but not sold here.','NPS Military',247);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Must show pass upon entry.  Admits 4th grader pass holder and up to three adults.  Pass accepted for entry, but not sold here.','NPS Every Kid In a Park',248);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Membership must be current.','Theodore Roosevelt Inaugural Site Foundation member',249);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'no pass, no fee','no pass',250);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (55.00,'Entrance to all units of Theodore Roosevelt National Park for one year from month of purchase. Admits pass holder and passengers in a single, private, non-commercial vehicle, or the pass holder and his/her immediate family (spouse, children, parents) when entry is by other means (foot, bicycle, etc.).','Theodore Roosevelt National Park Annual Pass',251);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'Only valid at Thomas Edison National Historical Park for 12 months from the date of purchase. This pass admits the pass holder and three (3) additional adult guests into the park free of charge. All visitors 15 years old and under are free. Buy your pass online Recreation.gov. 

Important Note: Entering the park using an Edison Annual Park Pass does not guarantee entry into the Edison Home, Glenmont. Tickets are available on a first-come basis only.

** Early arrival is strongly advised.**','Thomas Edison NHP Park Specific Annual Pass - Credit or Debit Card only',252);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',253);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'None','Passes',254);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Covers pass holder(s) plus three adult guests. Kids under 16 are always free. Photo ID of either pass holder required. Valid for 12 months from month of purchase.','Tumacácori Annual Pass',255);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'The Montezuma Castle and Tuzigoot Annual Pass covers the card holder and 3 other adults (aged 16 and over) into both Montezuma Castle and Tuzigoot for one year from date of purchase. Children 15 and under are free.','Tuzigoot and Montezuma Castle Annual Pass',256);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'Valid for one year from date of purchase; does not offer discounts at the cooperating association bookstores.','Vicksburg Annual Pass',257);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'No Passes','No Passes',258);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (5.00,'Trunk Bay Day Pass','Trunk Bay Day Pass',259);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (2.50,'Trunk Bay Senior Day Pass 
Fee for individual and up to 3 guests.','Trunk Bay Senior Day Pass',260);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (30.00,'Trunk Bay Family Annual Pass','Trunk Bay Family Annual Pass',261);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Trunk Bay Individual Annual Pass','Trunk Bay Individual Annual Pass',262);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Trunk Bay Annual Senior Pass','Trunk Bay Annual Senior Pass',263);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Trunk Bay Lifetime Senior Pass','Trunk Bay Lifetime Senior Pass',264);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Trunk Bay Access or Military Pass','Trunk Bay Access or Military Pass',265);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (26.00,'Mooring or anchoring overnight (From 5 p. m. to 7 a.m.)
Anchoring is only available in two locations.','Fee for Mooring Or Anchoring Overnight',266);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (13.00,'Mooring or anchoring overnight for seniors.
Anchoring is only available in two locations.','Fee for Mooring or Anchoring Overnight Seniors',267);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Mark your calendar for these entrance fee–free dates in 2017:
January 16: Martin Luther King Jr. Day
February 20: Presidents''Day
April 15-16 and 22-23:Weekends of National Park Week
August 25:National Park Service Birthday
September 30:National Public Lands Day
November 11-12:Veterans Day Weekend','Trunk Bay Free Days',268);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass is valid for one year from the month of purchase. At Walnut Canyon National Monument, it covers entry for up to four adults; children ages 15 and younger enter for free. At Sunset Crater Volcano and Wupatki National Monuments, it covers entry for all occupants of one private vehicle.','Flagstaff Annual Pass',269);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'The Washington Monument Lodge,located along 15th Street between Madison and Jefferson drives,opens at 8:45 a.m.for distribution of free,same day,timed tickets on a first-come,first-serve basis.One person may obtain up to six tickets as well as request their preferred ticket time.All visitors (including children ages 2+)must have a ticket to enter the Washington Monument.During peak season,tickets run out quickly and the line often forms long before the ticket window opens.','Same Day Walk Up Tickets (In Person)',270);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'30 Day Advance Reservations-Order tickets online up to a month in advance of your visit.Inventory for the next available day (30 days out)becomes available at 10 a.m.each morning (e.g.-on May 7 at 10 a.m.,tickets will become available for visits on June 6).Tickets sell out quickly after becoming available.

Reservations may be made at recreation.gov or by calling 877-444-6777.There is a $1.00 service charge per ticket;these fees are non-refundable.','30-Day Advance Reservations (Online Only)',271);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Didn ''t get tickets in advance or planning a last-minute visit? A limited number of additional tickets are made available at 10 a.m. each day for the next day''s visits (e.g.-on May 7 at 10 a.m.,tickets will become available for visits on May 8).

Reservations may be made at recreation.gov or by calling 877-444-6777.There is a $1.00 service charge per ticket;these fees are non-refundable.','24-Hour Advance Reservations (Online Only)',272);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (1.00,'Groups may reserve up to 55 tickets up to 30 days in advance at recreation.gov ONLY.No walk ups are available for group tours.There is a $1.00 service charge per ticket to cover the reservation service.','Group Tickets (Online Only)',273);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Available to everyone-may be purchased in the following manner:

-federal recreation sites
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)
-by phone at 888-ASK-USGS (1-888-275-8747)extension 3 (hours of operation are:8 am to 4 pm Mountain Time)
-online at the USGS store
-https://store.usgs.gov/pass','America the Beautiful Annual Pass',274);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available FREE for current U.S.military members and dependents in the Army,Navy,Air Force,Marines,and Coast Guard as well as Reserve and National Guard members-may be obtained in the following manner:

-federal recreation sites by showing a Common Access Card (CAC)or Military ID (Form 1173)
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)','Annual Pass for U.S.Military',275);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available FREE for U.S.4th graders (including home-schooled/free-choice learners 10 years of age)with a valid Every Kid in a Park paper pass (valid for duration of 4th grade year)

-may be obtained in the following manner:
-paper passes can be obtained by visiting the Every Kid in a Park website (https://www.everykidinapark.gov/)and exchanged for the Annual 4th Grade pass at federal recreation sites
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)','Annual 4th Grade Pass',276);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Available to U.S.citizens or permanent residents age 62 or over (must provide proof of age and residency/citizenship)-may be purchased in the following manner:

-federal recreation sites
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)
-by phone at 888-ASK-USGS (1-888-275-8747)extension 3 (hours of operation are:8 am to 4 pm Mountain Time)
-online at the USGS store
-https://store.usgs.gov/pass','Lifetime Senior Pass',277);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Available to U.S.citizens or permanent residents age 62 or over (must provide proof of age and residency/citizenship)-may be purchased in the following manner:

-federal recreation sites
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)
-by phone at 888-ASK-USGS (1-888-275-8747)extension 3 (hours of operation are:8 am to 4 pm Mountain Time)
-online at the USGS store
-https://store.usgs.gov/pass','Annual Senior Pass',278);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Available FREE to U.S.citizens or permanent residents with permanent disabilities (must provide proof of disability and residency/citizenship)-may be purchased in the following manner:

-federal recreation sites
-list of sites that issue passes (https://store.usgs.gov/sites/default/files/PassIssuanceList.pdf)
-by phone at 888-ASK-USGS (1-888-275-8747)extension 3 (hours of operation are:8 am to 4 pm Mountain Time)','Access Pass',279);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Gold Star Families and U.S.military veterans receive free access to more than 2,000 federal recreation areas,including national parks,wildlife refuges and forests.The free access program is a way to thank America’s veterans and Gold Star families for their support of our country and to encourage them to explore recreational opportunities on their public lands and waters.','Veterans&Gold Star Families',280);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass is valid for the card holder and three other adults within the same vehicle.Pass is good for one year from month of purchase.','White Sands Annual Pass',281);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Interagency Access Pass: Disability Pass issued for free with proof of disability.
Interagency Annual Military Pass: Issued for free to active-duty Military and dependents.
Interagency Lifetime Military Pass: Issued for free to Veterans and Gold Star families.
Interagency Every Kid Outdoors Pass: Issued for free to 4th grade students that go online and complete activity and print voucher from everykidoutdoors.gov website.','Free Passes Issued',282);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'As there is no fee associated with a visit, No Passes are required.','WWI Memorial Passes',283);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (35.00,'The annual pass (available for purchase at the entrance station) allows unlimited entry to Wright Brothers National Memorial for 12 months from date of purchase. Pass admits the passholder(s) + 3 adults (16 years of age and older).','Wright Brothers Annual Pass',284);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (45.00,'This pass is valid for one year from the month of purchase. At Sunset Crater Volcano and Wupatki National Monuments, it covers entry for all occupants of one private vehicle. At Walnut Canyon National Monument, it covers entry for up to four adults; children ages 15 and younger enter for free.','Flagstaff Annual Pass',285);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Annual pass providing free entrance into Yellowstone National Park for one year (valid through the month of purchase). On a snowmobile, this pass admits the signer(s). When traveling by snowcoach or shuttle, this pass admits a signer and up to three additional persons (16 and older) for a total of four people.','Yellowstone National Park Annual Pass',286);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (40.00,'The The Colonial annual pass admits passholder and three accompanying adults unlimited admittance to both NPS areas at Historic Jamestowne and Yorktown Battlefield during regular operating hours. Pass is valid for twelve months from the month of purchase. Note: There is an additional $5.00 Preservation Virginia entrance fee for each adult entering on the Colonial Pass to Historic Jamestowne to visit the Preservation Virginia historic areas.','Colonial National Historical Park Annual Pass',287);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Annual pass providing free entrance to Yosemite for 12 months from the date of purchase.','Yosemite Annual Pass',288);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Annual pass covering entrance and standard amenity fees for national parks and other federal fee areas, valid for 12 months from date of purchase. This replaces the National Parks Pass and Golden Eagle Pass.','America the Beautiful—National Parks and Federal Recreational Lands Annual Pass',289);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Lifetime or annual admission and discount pass for US citizens or permanent residents who are age 62 or older. An annual version of this pass, valid for 12 months, costs $20.','Senior Pass',290);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Lifetime admission and discount pass for US citizens or permanent residents with permanent disabilities.','Access Pass',291);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Annual pass covering entrance and standard amenity fees for all active US military personnel and their dependents, valid for 12 months from date of issuance. (For active duty military personnel and dependents with proper identification (CAC Card or DD Form 1173).)','Annual Pass for US Military',292);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Annual pass covering entrance fees for 4th grade students for 2018–2019 school year.','Annual 4th Grade Pass',293);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'There is no entrance fee for Yucca House National Monument. No passes are available.','No Entrance Pass is available.',294);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Admission to all Federal fee areas for one year from date of purchase.','Interagency Annual Pass',295);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (70.00,'Admission to Zion National Park for one year from date of purchase.','Zion Annual Pass',296);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (20.00,'Admission to all federal fee areas for one year from date of purchase.','Annual Senior Pass',297);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (80.00,'Admission to all federal fee areas for life, U.S. citizens 62 years or older.','Lifetime Senior Pass',298);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Admission to all federal fee areas for life, permanently disabled U.S. citizens','Lifetime Access Pass',299);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Since Veterans Day 2020, Gold Star Families and US military veterans are eligible to receive free access to more than 2,000 federal recreation areas, including national parks, wildlife refuges, and forests. The free access program is a way to thank America’s veterans, Gold Star Families, and current military and their dependents for their support of our country.

Learn more: https://www.nps.gov/planyourvisit/veterans-and-gold-star-families-free-access.htm','Free Access for Veterans and Gold Star Families',300);
INSERT INTO park_entrance_pass(cost,description,title,uid) VALUES (0.00,'Admission to all federal fee areas for one year from issue date. Volunteers with over 250 hours of service are eligible.','Volunteer Pass',301);
