DROP TABLE IF EXISTS park_topic;
CREATE TABLE park_topic(
   uid  INTEGER  NOT NULL PRIMARY KEY 
  ,name VARCHAR UNIQUE NOT NULL
);
INSERT INTO park_topic(uid,name) VALUES (1,'Birthplace');
INSERT INTO park_topic(uid,name) VALUES (2,'Presidents');
INSERT INTO park_topic(uid,name) VALUES (3,'Animals');
INSERT INTO park_topic(uid,name) VALUES (4,'Birds');
INSERT INTO park_topic(uid,name) VALUES (5,'Caves, Caverns and Karst');
INSERT INTO park_topic(uid,name) VALUES (6,'Geology');
INSERT INTO park_topic(uid,name) VALUES (7,'Groundwater');
INSERT INTO park_topic(uid,name) VALUES (8,'Freshwater Springs');
INSERT INTO park_topic(uid,name) VALUES (9,'Night Sky');
INSERT INTO park_topic(uid,name) VALUES (10,'Arts');
INSERT INTO park_topic(uid,name) VALUES (11,'Painting');
INSERT INTO park_topic(uid,name) VALUES (12,'Photography');
INSERT INTO park_topic(uid,name) VALUES (13,'Poetry and Literature');
INSERT INTO park_topic(uid,name) VALUES (14,'Sculpture');
INSERT INTO park_topic(uid,name) VALUES (15,'Colonization and Settlement');
INSERT INTO park_topic(uid,name) VALUES (16,'Maritime');
INSERT INTO park_topic(uid,name) VALUES (17,'Lighthouses');
INSERT INTO park_topic(uid,name) VALUES (18,'Monuments and Memorials');
INSERT INTO park_topic(uid,name) VALUES (19,'Schools and Education');
INSERT INTO park_topic(uid,name) VALUES (20,'Transportation');
INSERT INTO park_topic(uid,name) VALUES (21,'Bridges');
INSERT INTO park_topic(uid,name) VALUES (22,'Roads, Routes and Highways');
INSERT INTO park_topic(uid,name) VALUES (23,'Tragic Events');
INSERT INTO park_topic(uid,name) VALUES (24,'Catastrophic Fires');
INSERT INTO park_topic(uid,name) VALUES (25,'Women''s History');
INSERT INTO park_topic(uid,name) VALUES (26,'Fish');
INSERT INTO park_topic(uid,name) VALUES (27,'Climate Change');
INSERT INTO park_topic(uid,name) VALUES (28,'Fire');
INSERT INTO park_topic(uid,name) VALUES (29,'Forests and Woodlands');
INSERT INTO park_topic(uid,name) VALUES (30,'Lakes');
INSERT INTO park_topic(uid,name) VALUES (31,'Mountains');
INSERT INTO park_topic(uid,name) VALUES (32,'Astronomy');
INSERT INTO park_topic(uid,name) VALUES (33,'Oceans');
INSERT INTO park_topic(uid,name) VALUES (34,'Rock Landscapes and Features');
INSERT INTO park_topic(uid,name) VALUES (35,'Trails');
INSERT INTO park_topic(uid,name) VALUES (36,'Wetlands');
INSERT INTO park_topic(uid,name) VALUES (37,'American Revolution');
INSERT INTO park_topic(uid,name) VALUES (38,'African American Heritage');
INSERT INTO park_topic(uid,name) VALUES (39,'Wars and Conflicts');
INSERT INTO park_topic(uid,name) VALUES (40,'Civil War');
INSERT INTO park_topic(uid,name) VALUES (41,'Archeology');
INSERT INTO park_topic(uid,name) VALUES (42,'Burial, Cemetery and Gravesite');
INSERT INTO park_topic(uid,name) VALUES (43,'Enslavement');
INSERT INTO park_topic(uid,name) VALUES (44,'Social Movements');
INSERT INTO park_topic(uid,name) VALUES (45,'Urban America');
INSERT INTO park_topic(uid,name) VALUES (46,'Farming and  Agriculture');
INSERT INTO park_topic(uid,name) VALUES (47,'Ranches');
INSERT INTO park_topic(uid,name) VALUES (48,'Native American Heritage');
INSERT INTO park_topic(uid,name) VALUES (49,'Westward Expansion');
INSERT INTO park_topic(uid,name) VALUES (50,'Homesteading');
INSERT INTO park_topic(uid,name) VALUES (51,'Tortoises and Turtles');
INSERT INTO park_topic(uid,name) VALUES (52,'Fossils and Paleontology');
INSERT INTO park_topic(uid,name) VALUES (53,'Grasslands');
INSERT INTO park_topic(uid,name) VALUES (54,'Prairies');
INSERT INTO park_topic(uid,name) VALUES (55,'River and Riparian');
INSERT INTO park_topic(uid,name) VALUES (56,'Scenic Views');
INSERT INTO park_topic(uid,name) VALUES (57,'Architecture and Building');
INSERT INTO park_topic(uid,name) VALUES (58,'Ruins');
INSERT INTO park_topic(uid,name) VALUES (59,'Explorers and Expeditions');
INSERT INTO park_topic(uid,name) VALUES (60,'Pacific Islander Heritage');
INSERT INTO park_topic(uid,name) VALUES (61,'Religion and Spirituality');
INSERT INTO park_topic(uid,name) VALUES (62,'Heiau');
INSERT INTO park_topic(uid,name) VALUES (63,'Ancient Seas');
INSERT INTO park_topic(uid,name) VALUES (64,'Coasts, Islands and Atolls');
INSERT INTO park_topic(uid,name) VALUES (65,'Rainforest');
INSERT INTO park_topic(uid,name) VALUES (66,'Coral Reefs');
INSERT INTO park_topic(uid,name) VALUES (67,'The Tropics');
INSERT INTO park_topic(uid,name) VALUES (68,'Volcanoes');
INSERT INTO park_topic(uid,name) VALUES (69,'Waterfalls');
INSERT INTO park_topic(uid,name) VALUES (70,'Arctic');
INSERT INTO park_topic(uid,name) VALUES (71,'Tundra');
INSERT INTO park_topic(uid,name) VALUES (72,'Wilderness');
INSERT INTO park_topic(uid,name) VALUES (73,'Forts');
INSERT INTO park_topic(uid,name) VALUES (74,'Incarceration');
INSERT INTO park_topic(uid,name) VALUES (75,'Jails and Prisons');
INSERT INTO park_topic(uid,name) VALUES (76,'Maritime - Military');
INSERT INTO park_topic(uid,name) VALUES (77,'Medicine');
INSERT INTO park_topic(uid,name) VALUES (78,'Hospital');
INSERT INTO park_topic(uid,name) VALUES (79,'Military');
INSERT INTO park_topic(uid,name) VALUES (80,'US Army');
INSERT INTO park_topic(uid,name) VALUES (81,'Tribal Conflicts');
INSERT INTO park_topic(uid,name) VALUES (82,'Aviation');
INSERT INTO park_topic(uid,name) VALUES (83,'Coastal Defenses');
INSERT INTO park_topic(uid,name) VALUES (84,'Ships and Shipwrecks');
INSERT INTO park_topic(uid,name) VALUES (85,'US Navy');
INSERT INTO park_topic(uid,name) VALUES (86,'US Marines');
INSERT INTO park_topic(uid,name) VALUES (87,'US Coast Guard');
INSERT INTO park_topic(uid,name) VALUES (88,'US Air Force (Army Air Corps)');
INSERT INTO park_topic(uid,name) VALUES (89,'Indigenous and Native Warrior');
INSERT INTO park_topic(uid,name) VALUES (90,'Battlefields');
INSERT INTO park_topic(uid,name) VALUES (91,'Forced Marches');
INSERT INTO park_topic(uid,name) VALUES (92,'Massacres');
INSERT INTO park_topic(uid,name) VALUES (93,'World War II');
INSERT INTO park_topic(uid,name) VALUES (94,'Commerce');
INSERT INTO park_topic(uid,name) VALUES (95,'Trade');
INSERT INTO park_topic(uid,name) VALUES (96,'Engineering');
INSERT INTO park_topic(uid,name) VALUES (97,'Industry');
INSERT INTO park_topic(uid,name) VALUES (98,'Logging and Timber Cutting');
INSERT INTO park_topic(uid,name) VALUES (99,'Laborer and Worker');
INSERT INTO park_topic(uid,name) VALUES (100,'Infantry and Militia');
INSERT INTO park_topic(uid,name) VALUES (101,'Abolition Movement');
INSERT INTO park_topic(uid,name) VALUES (102,'Canals');
INSERT INTO park_topic(uid,name) VALUES (103,'Trains and Railroads');
INSERT INTO park_topic(uid,name) VALUES (104,'Murders');
INSERT INTO park_topic(uid,name) VALUES (105,'Mexican War');
INSERT INTO park_topic(uid,name) VALUES (106,'Japanese-American Internment');
INSERT INTO park_topic(uid,name) VALUES (107,'Estuaries and Mangroves');
INSERT INTO park_topic(uid,name) VALUES (108,'Asian American Heritage');
INSERT INTO park_topic(uid,name) VALUES (109,'Hispanic American Heritage');
INSERT INTO park_topic(uid,name) VALUES (110,'Migrant Workers');
INSERT INTO park_topic(uid,name) VALUES (111,'Latino American Heritage');
INSERT INTO park_topic(uid,name) VALUES (112,'Indian and Frontier Wars');
INSERT INTO park_topic(uid,name) VALUES (113,'Canyons and Canyonlands');
INSERT INTO park_topic(uid,name) VALUES (114,'War of 1812');
INSERT INTO park_topic(uid,name) VALUES (115,'Water Trails');
INSERT INTO park_topic(uid,name) VALUES (116,'National Cemetery');
INSERT INTO park_topic(uid,name) VALUES (117,'French and Indian War');
INSERT INTO park_topic(uid,name) VALUES (118,'American Revolutionary War');
INSERT INTO park_topic(uid,name) VALUES (119,'Spanish-American War');
INSERT INTO park_topic(uid,name) VALUES (120,'World War I');
INSERT INTO park_topic(uid,name) VALUES (121,'Korean War');
INSERT INTO park_topic(uid,name) VALUES (122,'Vietnam War');
INSERT INTO park_topic(uid,name) VALUES (123,'Cold War');
INSERT INTO park_topic(uid,name) VALUES (124,'Reconstruction');
INSERT INTO park_topic(uid,name) VALUES (125,'Geothermal');
INSERT INTO park_topic(uid,name) VALUES (126,'Artillery');
INSERT INTO park_topic(uid,name) VALUES (127,'Conservation Movement');
INSERT INTO park_topic(uid,name) VALUES (128,'Coniferous Forests');
INSERT INTO park_topic(uid,name) VALUES (129,'Deciduous Forests');
INSERT INTO park_topic(uid,name) VALUES (130,'Natural Sounds');
INSERT INTO park_topic(uid,name) VALUES (131,'Aurora Borealis');
INSERT INTO park_topic(uid,name) VALUES (132,'Unique Species');
INSERT INTO park_topic(uid,name) VALUES (133,'Endangered');
INSERT INTO park_topic(uid,name) VALUES (134,'Horses (wild)');
INSERT INTO park_topic(uid,name) VALUES (135,'Watersheds');
INSERT INTO park_topic(uid,name) VALUES (136,'Headwaters');
INSERT INTO park_topic(uid,name) VALUES (137,'Cavalry');
INSERT INTO park_topic(uid,name) VALUES (138,'Music');
INSERT INTO park_topic(uid,name) VALUES (139,'Arches');
INSERT INTO park_topic(uid,name) VALUES (140,'Immigration');
INSERT INTO park_topic(uid,name) VALUES (141,'Migrations');
INSERT INTO park_topic(uid,name) VALUES (142,'Colonial/European Contact Conflicts');
INSERT INTO park_topic(uid,name) VALUES (143,'Alligators or Crocodiles');
INSERT INTO park_topic(uid,name) VALUES (144,'Civil Rights');
INSERT INTO park_topic(uid,name) VALUES (145,'Dunes');
INSERT INTO park_topic(uid,name) VALUES (146,'Rare');
INSERT INTO park_topic(uid,name) VALUES (147,'Bison');
INSERT INTO park_topic(uid,name) VALUES (148,'Cats (wild)');
INSERT INTO park_topic(uid,name) VALUES (149,'Cliff Dwellings');
INSERT INTO park_topic(uid,name) VALUES (150,'Elk');
INSERT INTO park_topic(uid,name) VALUES (151,'Foothills, Plains and Valleys');
INSERT INTO park_topic(uid,name) VALUES (152,'Plateaus and Mesas');
INSERT INTO park_topic(uid,name) VALUES (153,'Voting Rights and Suffrage');
INSERT INTO park_topic(uid,name) VALUES (154,'Marshes');
INSERT INTO park_topic(uid,name) VALUES (155,'Hot Springs');
INSERT INTO park_topic(uid,name) VALUES (156,'Mining');
INSERT INTO park_topic(uid,name) VALUES (157,'Dinosaur');
INSERT INTO park_topic(uid,name) VALUES (158,'Swamps');
INSERT INTO park_topic(uid,name) VALUES (159,'Thickets and Shrublands');
INSERT INTO park_topic(uid,name) VALUES (160,'Dams');
INSERT INTO park_topic(uid,name) VALUES (161,'Churches');
INSERT INTO park_topic(uid,name) VALUES (162,'Explosions');
INSERT INTO park_topic(uid,name) VALUES (163,'Piracy and Privateering');
INSERT INTO park_topic(uid,name) VALUES (164,'Landscape Design');
INSERT INTO park_topic(uid,name) VALUES (165,'Tunnels');
INSERT INTO park_topic(uid,name) VALUES (166,'Plantations');
INSERT INTO park_topic(uid,name) VALUES (167,'Meadows');
INSERT INTO park_topic(uid,name) VALUES (168,'Whales');
INSERT INTO park_topic(uid,name) VALUES (169,'The Gold Rush');
INSERT INTO park_topic(uid,name) VALUES (170,'Impact Craters');
INSERT INTO park_topic(uid,name) VALUES (171,'Science, Technology and Innovation');
INSERT INTO park_topic(uid,name) VALUES (172,'Assassinations');
INSERT INTO park_topic(uid,name) VALUES (173,'Petrified Wood');
INSERT INTO park_topic(uid,name) VALUES (174,'Mineral Deposits');
INSERT INTO park_topic(uid,name) VALUES (175,'Glaciers');
INSERT INTO park_topic(uid,name) VALUES (176,'Great Depression');
INSERT INTO park_topic(uid,name) VALUES (177,'Mills');
INSERT INTO park_topic(uid,name) VALUES (178,'Religious Freedom');
INSERT INTO park_topic(uid,name) VALUES (179,'Floods');
INSERT INTO park_topic(uid,name) VALUES (180,'Aquifers');
INSERT INTO park_topic(uid,name) VALUES (181,'Factories');
INSERT INTO park_topic(uid,name) VALUES (182,'Armories');
INSERT INTO park_topic(uid,name) VALUES (183,'Wolves');
INSERT INTO park_topic(uid,name) VALUES (184,'Farming and Agriculture');
INSERT INTO park_topic(uid,name) VALUES (185,'Labor Movement');
INSERT INTO park_topic(uid,name) VALUES (186,'Buttes');
INSERT INTO park_topic(uid,name) VALUES (187,'Missions');
INSERT INTO park_topic(uid,name) VALUES (188,'LGBTQ American Heritage');
INSERT INTO park_topic(uid,name) VALUES (189,'Banking');
INSERT INTO park_topic(uid,name) VALUES (190,'Caves,Caverns and Karst');
INSERT INTO park_topic(uid,name) VALUES (191,'Roads,Routes and Highways');
INSERT INTO park_topic(uid,name) VALUES (192,'Coasts,Islands and Atolls');
INSERT INTO park_topic(uid,name) VALUES (193,'Maritime-Military');
INSERT INTO park_topic(uid,name) VALUES (194,'Science,Technology and Innovation');
INSERT INTO park_topic(uid,name) VALUES (195,'Burial,Cemetery and Gravesite');
INSERT INTO park_topic(uid,name) VALUES (196,'Foothills,Plains and Valleys');
INSERT INTO park_topic(uid,name) VALUES (197,'Women ''s History');
INSERT INTO park_topic(uid,name) VALUES (198,'Geysers');
