DROP TABLE IF EXISTS park_activity;
CREATE TABLE park_activity(
   uid  INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,name VARCHAR(40)
);
INSERT INTO park_activity(uid,name) VALUES (1,'Astronomy');
INSERT INTO park_activity(uid,name) VALUES (2,'Stargazing');
INSERT INTO park_activity(uid,name) VALUES (3,'Food');
INSERT INTO park_activity(uid,name) VALUES (4,'Picnicking');
INSERT INTO park_activity(uid,name) VALUES (5,'Guided Tours');
INSERT INTO park_activity(uid,name) VALUES (6,'Self-Guided Tours - Walking');
INSERT INTO park_activity(uid,name) VALUES (7,'Hands-On');
INSERT INTO park_activity(uid,name) VALUES (8,'Junior Ranger Program');
INSERT INTO park_activity(uid,name) VALUES (9,'Wildlife Watching');
INSERT INTO park_activity(uid,name) VALUES (10,'Birdwatching');
INSERT INTO park_activity(uid,name) VALUES (11,'Park Film');
INSERT INTO park_activity(uid,name) VALUES (12,'Museum Exhibits');
INSERT INTO park_activity(uid,name) VALUES (13,'Shopping');
INSERT INTO park_activity(uid,name) VALUES (14,'Bookstore and Park Store');
INSERT INTO park_activity(uid,name) VALUES (15,'Gift Shop and Souvenirs');
INSERT INTO park_activity(uid,name) VALUES (16,'Arts and Culture');
INSERT INTO park_activity(uid,name) VALUES (17,'Cultural Demonstrations');
INSERT INTO park_activity(uid,name) VALUES (18,'Biking');
INSERT INTO park_activity(uid,name) VALUES (19,'Boating');
INSERT INTO park_activity(uid,name) VALUES (20,'Camping');
INSERT INTO park_activity(uid,name) VALUES (21,'Group Camping');
INSERT INTO park_activity(uid,name) VALUES (22,'Climbing');
INSERT INTO park_activity(uid,name) VALUES (23,'Rock Climbing');
INSERT INTO park_activity(uid,name) VALUES (24,'Compass and GPS');
INSERT INTO park_activity(uid,name) VALUES (25,'Geocaching');
INSERT INTO park_activity(uid,name) VALUES (26,'Fishing');
INSERT INTO park_activity(uid,name) VALUES (27,'Freshwater Fishing');
INSERT INTO park_activity(uid,name) VALUES (28,'Fly Fishing');
INSERT INTO park_activity(uid,name) VALUES (29,'Saltwater Fishing');
INSERT INTO park_activity(uid,name) VALUES (30,'Bus/Shuttle Guided Tour');
INSERT INTO park_activity(uid,name) VALUES (31,'Boat Tour');
INSERT INTO park_activity(uid,name) VALUES (32,'Citizen Science');
INSERT INTO park_activity(uid,name) VALUES (33,'Hiking');
INSERT INTO park_activity(uid,name) VALUES (34,'Front-Country Hiking');
INSERT INTO park_activity(uid,name) VALUES (35,'Horse Trekking');
INSERT INTO park_activity(uid,name) VALUES (36,'Horseback Riding');
INSERT INTO park_activity(uid,name) VALUES (37,'Ice Skating');
INSERT INTO park_activity(uid,name) VALUES (38,'Paddling');
INSERT INTO park_activity(uid,name) VALUES (39,'Canoeing');
INSERT INTO park_activity(uid,name) VALUES (40,'Kayaking');
INSERT INTO park_activity(uid,name) VALUES (41,'Stand Up Paddleboarding');
INSERT INTO park_activity(uid,name) VALUES (42,'Skiing');
INSERT INTO park_activity(uid,name) VALUES (43,'Cross-Country Skiing');
INSERT INTO park_activity(uid,name) VALUES (44,'Snow Play');
INSERT INTO park_activity(uid,name) VALUES (45,'Snowmobiling');
INSERT INTO park_activity(uid,name) VALUES (46,'Snowshoeing');
INSERT INTO park_activity(uid,name) VALUES (47,'Swimming');
INSERT INTO park_activity(uid,name) VALUES (48,'Freshwater Swimming');
INSERT INTO park_activity(uid,name) VALUES (49,'Saltwater Swimming');
INSERT INTO park_activity(uid,name) VALUES (50,'Living History');
INSERT INTO park_activity(uid,name) VALUES (51,'First Person Interpretation');
INSERT INTO park_activity(uid,name) VALUES (52,'Auto and ATV');
INSERT INTO park_activity(uid,name) VALUES (53,'Scenic Driving');
INSERT INTO park_activity(uid,name) VALUES (54,'Mountain Biking');
INSERT INTO park_activity(uid,name) VALUES (55,'Road Biking');
INSERT INTO park_activity(uid,name) VALUES (56,'Motorized Boating');
INSERT INTO park_activity(uid,name) VALUES (57,'Sailing');
INSERT INTO park_activity(uid,name) VALUES (58,'Canoe or Kayak Camping');
INSERT INTO park_activity(uid,name) VALUES (59,'Car or Front Country Camping');
INSERT INTO park_activity(uid,name) VALUES (60,'RV Camping');
INSERT INTO park_activity(uid,name) VALUES (61,'Orienteering');
INSERT INTO park_activity(uid,name) VALUES (62,'Self-Guided Tours - Auto');
INSERT INTO park_activity(uid,name) VALUES (63,'Arts and Crafts');
INSERT INTO park_activity(uid,name) VALUES (64,'SCUBA Diving');
INSERT INTO park_activity(uid,name) VALUES (65,'Snorkeling');
INSERT INTO park_activity(uid,name) VALUES (66,'Surfing');
INSERT INTO park_activity(uid,name) VALUES (67,'Backcountry Camping');
INSERT INTO park_activity(uid,name) VALUES (68,'Hunting and Gathering');
INSERT INTO park_activity(uid,name) VALUES (69,'Hunting');
INSERT INTO park_activity(uid,name) VALUES (70,'Whitewater Rafting');
INSERT INTO park_activity(uid,name) VALUES (71,'Craft Demonstrations');
INSERT INTO park_activity(uid,name) VALUES (72,'Historic Weapons Demonstration');
INSERT INTO park_activity(uid,name) VALUES (73,'Theater');
INSERT INTO park_activity(uid,name) VALUES (74,'Jet Skiing');
INSERT INTO park_activity(uid,name) VALUES (75,'Water Skiing');
INSERT INTO park_activity(uid,name) VALUES (76,'Playground');
INSERT INTO park_activity(uid,name) VALUES (77,'Team Sports');
INSERT INTO park_activity(uid,name) VALUES (78,'Reenactments');
INSERT INTO park_activity(uid,name) VALUES (79,'Mountain Climbing');
INSERT INTO park_activity(uid,name) VALUES (80,'Flying');
INSERT INTO park_activity(uid,name) VALUES (81,'Backcountry Hiking');
INSERT INTO park_activity(uid,name) VALUES (82,'Volunteer Vacation');
INSERT INTO park_activity(uid,name) VALUES (83,'Canyoneering');
INSERT INTO park_activity(uid,name) VALUES (84,'Auto Off-Roading');
INSERT INTO park_activity(uid,name) VALUES (85,'Horse Camping (see also Horse/Stock Use)');
INSERT INTO park_activity(uid,name) VALUES (86,'Off-Trail Permitted Hiking');
INSERT INTO park_activity(uid,name) VALUES (87,'Horse Camping (see also camping)');
INSERT INTO park_activity(uid,name) VALUES (88,'Dining');
INSERT INTO park_activity(uid,name) VALUES (89,'Tubing');
INSERT INTO park_activity(uid,name) VALUES (90,'Snow Tubing');
INSERT INTO park_activity(uid,name) VALUES (91,'Dog Sledding');
INSERT INTO park_activity(uid,name) VALUES (92,'Fixed Wing Flying');
INSERT INTO park_activity(uid,name) VALUES (93,'Gathering and Foraging');
INSERT INTO park_activity(uid,name) VALUES (94,'ATV Off-Roading');
INSERT INTO park_activity(uid,name) VALUES (95,'Pool Swimming');
INSERT INTO park_activity(uid,name) VALUES (96,'Live Music');
INSERT INTO park_activity(uid,name) VALUES (97,'Caving');
INSERT INTO park_activity(uid,name) VALUES (98,'Golfing');
INSERT INTO park_activity(uid,name) VALUES (99,'River Tubing');
INSERT INTO park_activity(uid,name) VALUES (100,'Ice Climbing');
INSERT INTO park_activity(uid,name) VALUES (101,'Downhill Skiing');
INSERT INTO park_activity(uid,name) VALUES (102,'Helicopter Flying');
INSERT INTO park_activity(uid,name) VALUES (103,'Mini-Golfing');
INSERT INTO park_activity(uid,name) VALUES (104,'Self-Guided Tours-Walking');
INSERT INTO park_activity(uid,name) VALUES (105,'Self-Guided Tours-Auto');
INSERT INTO park_activity(uid,name) VALUES (106,'Planetarium');
