DROP TABLE IF EXISTS park_email;
CREATE TABLE park_email(
   description  VARCHAR(504)
  ,emailAddress VARCHAR(44)
  ,uid          INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ABLI_Administration@nps.gov',1);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'acadia_information@nps.gov',2);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ADAM_Visitor_Center@nps.gov',3);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',4);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'african_burial_ground@nps.gov',5);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'agfo_ranger_activities@nps.gov',6);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'aric_arakaki@nps.gov',7);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'KATM_Visitor_Information@nps.gov',8);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'anch_web_mail@nps.gov',9);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'goga_alca_socialmedia@nps.gov',10);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'rachel_mason@nps.gov',11);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lamr_interpretation@nps.gov',12);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'alpo_interpretation@nps.gov',13);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park Information','Amache_visitor_information@nps.gov',14);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'AMME_Administration@nps.gov',15);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'amis_interpretation@nps.gov',16);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nace_superintendent@nps.gov',17);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ande_information@nps.gov',18);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park information email','anjo_information@nps.gov',19);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'KATM_Visitor_Information@nps.gov',20);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'anti_info@nps.gov',21);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'apis_information@nps.gov',22);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'0@0',23);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'APCO_SocialMedia@nps.gov',24);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'archinfo@nps.gov',25);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'teresa_donaldson@nps.gov',26);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_superintendent@nps.gov',27);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'asis_information@nps.gov',28);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'azru_information@nps.gov',29);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'badl_information@nps.gov',30);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'john_reid@nps.gov',31);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park email for any questions about monument operations.','band_visitor_center@nps.gov',32);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General vistor inquiries','bepa_info@nps.gov',33);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'beol_interpretation@nps.gov',34);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bela_interpretation@nps.gov',35);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bibe_info@nps.gov',36);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bicy_information@nps.gov',37);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'biho_visitor_information@nps.gov',38);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'biso_information@nps.gov',39);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('We usually reply to emails within one week.','bith_information@nps.gov',40);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'BICA_media@nps.gov',41);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Birmingham Civil Rights National Monument Informational Inbox','bicr_information@nps.gov',42);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('If you can\'t find what you are looking for on the park website then e-mail us at bisc_information@nps.gov.','bisc_information@nps.gov',43);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('We will try to respond to your inquiry within one week. Answers to most questions can be found on this website, particularly under the Plan Your Visit menu (above).','blca_info@nps.gov',44);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'blrv_info@nps.gov',45);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Blackwell_school_visitor_information@nps.gov',46);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'blri_info@nps.gov',47);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'neri_interpretation@nps.gov',48);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bowa_rangers_3@nps.gov',49);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please use this email for general inquiries.','boaf_mail@nps.gov',50);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'BOHA_Information@nps.gov',51);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'BOST_Email@nps.gov',52);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('For a quicker response please call the Parkway Visitor Center at 1-800-305-7417. A park ranger is available 7 days a week during business hours to answer your questions about the park. The visitor center is closed Thanksgiving, December 25th and January 1st.','natr_interpretation@nps.gov',53);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'BRVB_Special_Events@nps.gov',54);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'brca_information@nps.gov',55);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CHRI_Education@nps.gov',56);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'buff_information@nps.gov',57);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cabr_info@nps.gov',58);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',59);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cane_info@nps.gov',60);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CANA_Interpretation@nps.gov',61);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cari_interp@nps.gov',62);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cach_interpretation@nps.gov',63);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('We check this email inbox at least once a week. We will respond to your email as soon as we can.','canyinfo@nps.gov',64);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'caco_information@nps.gov',65);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'caha_public_affairs@nps.gov',66);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Michael_Byrd@nps.gov',67);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wear_webmail@nps.gov',68);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CALO_Information@nps.gov',69);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nace_superintendent@nps.gov',70);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'care_information@nps.gov',71);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cajo_info@nps.gov',72);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General mailbox of the Capulin Volcano National Monument Interpretation and Visitor Services staff.','cavo_interpretation@nps.gov',73);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'carl_administration@nps.gov',74);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cave_park_information@nps.gov',75);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nace_superintendent@nps.gov',76);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park information and specific questions will be received at this email address and answered by appropriate park staff.','cagr_ranger_activities@nps.gov',77);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'casa_ranger_activities@nps.gov',78);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'laura_brennan@nps.gov',79);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'MOJA_Superintendent@nps.gov',80);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CATO_superintendent@nps.gov',81);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cedarbreaksinfo@nps.gov',82);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cebe_information@nps.gov',83);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chcu_information@nps.gov',84);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cham_information@nps.gov',85);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chis_information@nps.gov',86);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chpi_information@nps.gov',87);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park information email.','chyo_info@nps.gov',88);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Use this email address to contact the park. Once received your email will be directed to the appropriate person to assist you. If you should know the email address of the person you wish to contact please use it.','chat_superintendent@nps.gov',89);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Chesapeake &Ohio Canal General Email Inbox','CHOH_Information@nps.gov',90);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chesapeake_info@nps.gov',91);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chch_information@nps.gov',92);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ron_parker@nps.gov',93);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chir_interpretation@nps.gov',94);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CHRI_Education@nps.gov',95);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ciro_superintendent@nps.gov',96);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kenya_finley@nps.gov',97);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_clara_barton_nhs@nps.gov',98);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'COLO_Info@nps.gov',99);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'colm_info@nps.gov',100);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park information and requests.','colt@nps.gov',101);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cong_information@nps.gov',102);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',103);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'coro_interpretation@nps.gov',104);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'COWP_information@nps.gov',105);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'craterlake@nps.gov',106);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'crmo_information@nps.gov',107);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cuga_interpretation@nps.gov',108);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cuis_info@nps.gov',109);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cure_info@nps.gov',110);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'cuva_info@nps.gov',111);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nps_cech_administration@nps.gov',112);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ryan_qualls@nps.gov',113);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'deso_interpretive_staff@nps.gov',114);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'deva_information@nps.gov',115);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please use this email address for any park related questions. We will forward your information to the appropriate park representative that can answer your questions or address your concerns. We look forward to hearing from you.','dewa_interpretation@nps.gov',116);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'denali_info@nps.gov',117);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'depo_visitor_information@nps.gov',118);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Contact us for mailing requests and questions about the park.','deto_interpretation@nps.gov',119);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Main monument email for information','dino_information@nps.gov',120);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'drto_information@nps.gov',121);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email for all National Mall and Memorial Parks sites.','national_mall@nps.gov',122);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'clifford_deloreon@nps.gov',123);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'indevisitorinfo@nps.gov',124);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'efmo_interpretation@nps.gov',125);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gett_superintendent@nps.gov',126);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',127);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',128);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'elma_social_media@nps.gov',129);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wendy_gordge@nps.gov',130);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'margaret_laffin@nps.gov',131);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'stli_info@nps.gov',132);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'euon_general_info@nps.gov',133);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ever_information@nps.gov',134);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park information','vladimir_merzlyakov@nps.gov',135);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FIIS_Information@nps.gov',136);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FILA_info@nps.gov',137);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('We appreciate your patience as we are receiving an increase in inquiries and will respond as quickly as we can.','firststate@nps.gov',138);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'flni_superintendent@nps.gov',139);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'flfo_information@nps.gov',140);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fords_theatre@nps.gov',141);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'chir_interpretation@nps.gov',142);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FODA_Superintendent@nps.gov',143);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fodo_administration@nps.gov',144);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kenya_finley@nps.gov',145);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'pisc_superintendent@nps.gov',146);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FOFR_administration@nps.gov',147);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FOLA_Visitor_Information@nps.gov',148);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This e-mail address is monitored during park operating hours by a member of the ranger division. Most messages will be answered within 24 hours. Inquiries directed to facilities and maintenance staff may take additional time to receive a response, especially on weekends.','fols_internet@nps.gov',149);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'foma_site_supervisor@nps.gov',150);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FOMC_Interpretation@nps.gov',151);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fomr_interpretation@nps.gov',152);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fone_interpretation@nps.gov',153);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'goga_fopo_socialmedia@nps.gov',154);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fopu_information@nps.gov',155);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'caha_public_affairs@nps.gov',156);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fosc_interpretation@nps.gov',157);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fosm_parkinfo@nps.gov',158);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fost_info@nps.gov',159);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fosu_information@nps.gov',160);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'foun_information@nps.gov',161);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fous_socialmedia@nps.gov',162);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fova_information@nps.gov',163);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'PISC_Superintendent@nps.gov',164);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fobu_interpretation@nps.gov',165);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',166);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nace_superintendent@nps.gov',167);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'frla_interpretation@nps.gov',168);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'FRSP_Info@nps.gov',169);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'frri_information@nps.gov',170);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'frhi_superintendent@nps.gov',171);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fair_information@nps.gov',172);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jeff_superintendent@nps.gov',173);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'daphne_yun@nps.gov',174);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'neri_interpretation@nps.gov',175);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Contact us here for any park inquiries','gegr_info@nps.gov',176);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Contact park Staff','GERO_Ranger_Activities@nps.gov',177);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'GEWA_Superintendent@nps.gov',178);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwca_interpretation@nps.gov',179);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_superintendent@nps.gov',180);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'GETT_Superintendent@nps.gov',181);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gicl_information@nps.gov',182);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'glba_administration@nps.gov',183);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'glac_questions@nps.gov',184);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Glen Canyon Information.\nThis inbox is checked weekly.','glca_carl_hayden@nps.gov',185);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_glen_echo@nps.gov',186);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'indevisitorinfo@nps.gov',187);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'goga_socialmedia_goga@nps.gov',188);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gosp_interpretation@nps.gov',189);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Joseph_Korber@nps.gov',190);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'grca_information@nps.gov',191);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General questions','para_interpretation@nps.gov',192);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'grpo_information@nps.gov',193);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'grte_info@nps.gov',194);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'grko_interpretation@nps.gov',195);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'grba_interpretation@nps.gov',196);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'paul_kenney@nps.gov',197);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('GWMP Superintendent','gwmp_superintendent@nps.gov',198);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email a ranger to get your questions answered.','grsa_interpretation@nps.gov',199);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'GRSM_Smokies_Information@nps.gov',200);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'noel_harrison@nps.gov',201);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kevin_barry@nps.gov',202);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please note that most questions can be answered via the park website or on the NPS App.','gumo_information@nps.gov',203);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This email is the basic contact that will then be routed by the Administration to the appropriate staff member.','guco_administration@nps.gov',204);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'guis_information@nps.gov',205);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hafo_information@nps.gov',206);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hale_interpretation@nps.gov',207);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('generic email box for HAGR.','HAGR_info@nps.gov',208);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'HAMP_Interpretation@nps.gov',209);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'pisc_superintendent@nps.gov',210);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'harpersferry_info@nps.gov',211);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hart_information@nps.gov',212);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hatu_information@nps.gov',213);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'djrichardson@nps.gov',214);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'havo_information@nps.gov',215);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'heho_information@nps.gov',216);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'colo_info@nps.gov',217);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'margaret_laffin@nps.gov',218);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General mailbox for the public to contact the park.','home_information@nps.gov',219);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'pwr_honouliuli@nps.gov',220);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email for general park information.','hocu_info@nps.gov',221);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hofu_superintendent@nps.gov',222);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'HOBE_Information@nps.gov',223);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hosp_park_information@nps.gov',224);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'hoveinfo@nps.gov',225);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'HUTR_ranger_activities@nps.gov',226);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'iafl_program_manager@nps.gov',227);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'iatr_administration@nps.gov',228);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'indevisitorinfo@nps.gov',229);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'indu_communications@nps.gov',230);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'isro_parkinfo@nps.gov',231);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jeff_rasic@nps.gov',232);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jaga_interpretation@nps.gov',233);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jela_interpretation@nps.gov',234);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This email address connects online guests with staff at the visitor center. Every effort is made to respond to common questions and requests for information within 48 hours. However, some questions or requests for assistance may require input from other staff. In these instances, requests will be forwarded to the appropriate individual for a direct response.','jeca_information@nps.gov',235);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jica_information@nps.gov',236);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'joda_interpretation@nps.gov',237);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jason_atsales@nps.gov',238);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jomu_general_info@nps.gov',239);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Nathan_Koozer@nps.gov',240);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'jotr_info@nps.gov',241);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'juba_info@nps.gov',242);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kala_superintendent@nps.gov',243);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Supervisory Park Ranger- Interpretation.    Website and Social Media manager','Jon_Jokiel@nps.gov',244);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kaww_info@nps.gov',245);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'KATM_Visitor_Information@nps.gov',246);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kefjinformation@nps.gov',247);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email contact for the Superintendent: nace_superintendent@nps.gov','nace_superintendent@nps.gov',248);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kemo_administration@nps.gov',249);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kewe_information@nps.gov',250);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'KIMO_Information@nps.gov',251);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'klse_ranger_activities@nps.gov',252);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'klgo_information@nps.gov',253);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'KNRI_Information@nps.gov',254);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wear_webmail@nps.gov',255);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',256);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_superintendent@nps.gov',257);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lacl_visitor_information@nps.gov',258);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'LAKE_information@nps.gov',259);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lamr_interpretation@nps.gov',260);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Our rangers will get back to you as soon as possible with any questions or comments.','laro_web_master@nps.gov',261);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lavo_information@nps.gov',262);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('If you have a question or need some information sent to you, please drop us a line. We will get the information out as fast as we can.','LABE_Information@nps.gov',263);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lecl_information@nps.gov',264);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'LEWI_information@nps.gov',265);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'LIBO_superintendent@nps.gov',266);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'liho_information@nps.gov',267);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',268);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'marvin_dawes@nps.gov',269);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General information contact email address for Little River Canyon National Preserve.','liri_information@nps.gov',270);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email the park at this address for questions, directions, programming, or other general information. To reserve a guided tour, please call the park during business hours (9:00 a.m. to 5:00 p.m. CST/CDT, daily).','chsc_info@nps.gov',271);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'long_info@nps.gov',272);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lowe_public_information@nps.gov',273);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'sarah_bursky@nps.gov',274);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lestm@tenement.org',275);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'lyjo_information@nps.gov',276);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Benjamin_Anderson@nps.gov',277);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'acadia_information@nps.gov',278);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Primary email contact for Mammoth Cave National Park visitor information','maca_information@nps.gov',279);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'manassas_battlefield@nps.gov',280);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mapr_information@nps.gov',281);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Can\'t find what you\'re looking for on our website? Email us with general information requests.','manz_information_request@nps.gov',282);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mabi_visitorservices@nps.gov',283);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',284);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'MALU_Information@nps.gov',285);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mava_info@nps.gov',286);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bethuneNHS@nps.gov',287);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'MEMY_information@nps.gov',288);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'meve_general_information@nps.gov',289);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'benjamin_blevins@nps.gov',290);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Miin_information@nps.gov',291);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mima_info@nps.gov',292);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mimi_information@nps.gov',293);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This is the e-mail address for all Park-related questions. This account is checked daily with responses sent out within two days.','miss_info@nps.gov',294);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'thomas_downs@nps.gov',295);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'MOJA_Superintendent@nps.gov',296);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'mono_mail@nps.gov',297);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Paul_Santellan@nps.gov',298);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Get all your information needs here by sending a message to this Email.','mocr_information@nps.gov',299);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',300);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'morr_interpretation@nps.gov',301);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'morainfo@nps.gov',302);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park information.  Due to the volume of inquiries there may be a delay in getting a response.','moru_information@nps.gov',303);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'goga_muwo_socialmedia@nps.gov',304);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park Information','natc_superintendent@nps.gov',305);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('It is best to call the Natchez Trace Parkway Visitor Center at 1-800-305-7417. The visitor center is open 7 days a week during normal business hours. The visitor center is closed Thanksgiving, December 25th and January 1st.','natr_interpretation@nps.gov',306);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('For the quickest response please call the Parkway Visitor Center at 1-800-305-7417 during normal business hours','natr_interpretation@nps.gov',307);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'NACE_Superintendent@nps.gov',308);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',309);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'npsa_info@nps.gov',310);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Suzanne_McCarthy@nps.gov',311);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nabrinfo@nps.gov',312);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('E-mail Park Superintendent. No general park contact e-mail currently setup.','Lloyd_Masayumptewa@nps.gov',313);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nebe_info@nps.gov',314);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('For information regarding the NET in Massachusetts, contact Bridge Likely at amcnenst@outdoors.org\n\nFor information regarding the NET in Connecticut, contact Clare Cain at ccain@ctwoodlands.org','net@nps.gov',315);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ner_external_affairs@nps.gov',316);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email is generally answered within 48 hours.','jazz_interpretation@nps.gov',317);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'neri_interpretation@nps.gov',318);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nepe_superintendent@nps.gov',319);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nicodemusnhs@gmail.com',320);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'NISI_Information@nps.gov',321);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'niobrara_nsr@nps.gov',322);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wear_webmail@nps.gov',323);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'noca_information@nps.gov',324);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'NOCO_Administration@nps.gov',325);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'obri_information@nps.gov',326);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ocmu_administration@nps.gov',327);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'OKCI_superintendent@nps.gov',328);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',329);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'olym_visitor_center@nps.gov',330);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'orca_information@nps.gov',331);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('National Trails Office - Regions 6, 7, 8','ntir_information@nps.gov',332);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'orpi_information@nps.gov',333);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'OVVI_Information@nps.gov',334);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'PISC_Superintendent@nps.gov',335);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ozar_interpretation@nps.gov',336);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This is the primary park e-mail address for visitors to ask questions and get information about the park.','pais_visitor_center@nps.gov',337);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'paal_interpretation@nps.gov',338);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ilyse_goldman@nps.gov',339);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'PERI_interpretation@nps.gov',340);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'nps_valr_visitor_services@nps.gov',341);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'peco_visitor_information@nps.gov',342);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',343);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This email will go to our web and social media team and they will respond.','pevi_social_media@nps.gov',344);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Pete_Interpretation@nps.gov',345);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'PEFO_information@nps.gov',346);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'petr_interpretation@nps.gov',347);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'piro_information@nps.gov',348);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please include dates or season of your visit if applicable.We usually reply to emails within one week.For volunteer opportunities or service projects,please email pinn_volunteer@nps.gov.','pinn_visitor_information@nps.gov',349);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'PISP_interpretation@nps.gov',350);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'pipe_interpretation@nps.gov',351);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'pisc_superintendent@nps.gov',352);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please browse through this website (the Plan Your Visit section is very useful) and check out the Frequently Asked Questions before submitting your message. We receive a lot of emails requesting information that is available through our website. If you cannot find answers to your questions by browsing through our website, please feel free to send us an email. We will respond to emails in the order they are received. Due to the high volume of email, response to your message may take more than a week.','pore_info@nps.gov',353);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',354);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General Inquiry and reservations.','poch_general_info@nps.gov',355);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Emails are routed to the C&O Canal superintendent \'s office.','choh_superintendent@nps.gov',356);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'povertypoint@crt.la.gov',357);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('The Visitor Center includes temporary exhibit displays,a Jefferson National Parks Association bookstore/gift shop,and National Park Service staff to receive visitors and answer questions.\n\nNote:an internet search for the NHS tend to direct you to the\"Boyhood Home\"on 13th Street instead of the\"Birthplace Home.\"Use the NHS address at 117 S.Hervey Street on a GPS,etc.to reach the National Park Service site.','Wicl_Visitor_Center@nps.gov',358);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'presidents_park@nps.gov',359);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'goga_pres_socialmedia@nps.gov',360);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'prwi_info@nps.gov',361);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Email will be answered within 3-5 business days.','pull_visitorinfo@nps.gov',362);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'keola_awong@nps.gov',363);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'puhe_info@nps.gov',364);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park Information for Glen Canyon National Recreation Area and Rainbow Bridge National Monument. This box is checked weekly.','glca_carl_hayden@nps.gov',365);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'reer_information@nps.gov',366);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'redw_info@nps.gov',367);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'andrea_dekoter@nps.gov',368);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'bibe_info@nps.gov',369);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'shawna_mazur@nps.gov',370);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Click on the link to e-mail Rock Creek Park.','rocr_superintendent@nps.gov',371);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'romo_information@nps.gov',372);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Responses may take 1-2 business days. We apologize for any inconvenience this may cause.','rowi_info@nps.gov',373);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'info@fdr.net',374);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'rori_gen_info@nps.gov',375);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'RUCA_Information@nps.gov',376);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General inbox for Sagamore Hill NHS.','sahi_information@nps.gov',377);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'sagu_information@nps.gov',378);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'acadia_information@nps.gov',379);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SACN_Info@nps.gov',380);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'dho59stpaul@yahoo.com',381);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'saga_interpretation@nps.gov',382);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SAMA_Information@nps.gov',383);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'sapu_interp@nps.gov',384);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'CHRI_Education@nps.gov',385);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SAAN_Interpretation@nps.gov',386);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Thank you very much for your message! Our email account is monitored weekdays between 8 A.M. and 5 P.M. and we will respond to all messages within two business days.','ronald_robles@nps.gov',387);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'clifford_deloreon@nps.gov',388);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'saju_superintendent@nps.gov',389);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'sand_information@nps.gov',390);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ntir_information@nps.gov',391);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'samo_interpretation@nps.gov',392);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Saratoga National Historical Park information line.','SARA_info@nps.gov',393);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SAMA_Information@nps.gov',394);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'scbl_ranger_activities@nps.gov',395);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'semo_info@nps.gov',396);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SEKI_information@nps.gov',397);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Park information, lost and found and trip planning. Emails are answered on weekdays only, usually within 5 business days.','shen_info@nps.gov',398);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'shil_interpretation@nps.gov',399);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'SITK_Information_Requests@nps.gov',400);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'sleepingbearinfo@nps.gov',401);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'spar_interpretation@nps.gov',402);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Star-Spangled-Trail_info@nps.gov',403);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'stli_info@nps.gov',404);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'STGE_Visitor_Info@nps.gov',405);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('General park information','stea_visitor_information@nps.gov',406);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('stri_administration@nps.gov','stri_administration@nps.gov',407);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Stonewall@nps.gov',408);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'flag_information@nps.gov',409);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'tapr_interpretation@nps.gov',410);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Use the email for information about the site.','indevisitorinfo@nps.gov',411);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'thrb_info@nps.gov',412);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'info@trsite.org',413);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gwmp_superintendent@nps.gov',414);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'thro_interpretation@nps.gov',415);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'director@thomascole.org',416);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Please use this email to send us your questions/concerns.','edis.interpretation@gmail.com',417);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',418);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'gewa_thst_information@nps.gov',419);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'tica_info@nps.gov',420);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'timu_information@nps.gov',421);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('If you have general questions about Tonto National Monument and the cliff dwellings, please send us an email. We will respond as soon as possible.','tont_information@nps.gov',422);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'info@tourosynagogue.org',423);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('National Trails','ntir_information@nps.gov',424);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'TULE_Information@nps.gov',425);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'tusk_information@nps.gov',426);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'NPS_TUMA_Information@nps.gov',427);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('This is a general email box. It is checked Monday through Friday during business hours. It is best to call during business hours for a quicker response.','natr_interpretation@nps.gov',428);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'tuai_information@nps.gov',429);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'tuin_administration@nps.gov',430);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'paul_santellan@nps.gov',431);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'ulsg_interpretation@nps.gov',432);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'upde_interpretation@nps.gov',433);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'vall_info@nps.gov',434);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'vafo_superintendent@nps.gov',435);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'margaret_laffin@nps.gov',436);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'Vick_Interpretation@nps.gov',437);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',438);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Interpretation','viis_interpretation@nps.gov',439);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Interpretation Division Email.','viis_interpretation@nps.gov',440);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'VOYA_info@nps.gov',441);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'WACO_info@nps.gov',442);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'flag_information@nps.gov',443);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wapa_interpretation@nps.gov',444);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',445);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Washington-Rochambeau National Historic Trail','Johnny_Carawan@NPS.gov',446);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'waba_interpretation@nps.gov',447);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kristin_lessard@nps.gov',448);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'whis_information@nps.gov',449);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'whsa_interpretation@nps.gov',450);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'whmi_interpretation@nps.gov',451);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'kerry_wood@nps.gov',452);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'billie_aschwege@nps.gov',453);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'WICA_interpretation@nps.gov',454);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'visit@wingluke.org',455);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wotr_interp@nps.gov',456);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wori_information_desk@nps.gov',457);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('The email address for all National Mall and Memorial Park Sites.','National_Mall@nps.gov',458);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'national_mall@nps.gov',459);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'wrst_info@nps.gov',460);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'caha_public_affairs@nps.gov',461);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'flag_information@nps.gov',462);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('Contact Yellowstone\'s park rangers for general park questions, lost and found, or for special use permits.','YELL_Information@nps.gov',463);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'colo_info@nps.gov',464);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'yose_web_manager@nps.gov',465);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'meve_general_information@nps.gov',466);
INSERT INTO park_email(description,emailAddress,uid) VALUES (NULL,'fair_information@nps.gov',467);
INSERT INTO park_email(description,emailAddress,uid) VALUES ('If you cannot find what you need on our website, please write to ask for more information.','zion_park_information@nps.gov',468);
